# • Notebook “Day 10– Data Cleaning”
(showing handling of NaNs, filtering, and column manipulations)

# 1- Data Handling(Missing Values) using dropna & fillna:-

In [2]:
import pandas as pd

In [25]:
#Reading a CSV file-

#Titanic passengers csv.
csv=pd.read_csv("C:\\Users\\Prince Chandravat\\Downloads\\titanic.csv")  
csv

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [26]:
csv.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [27]:
#finding missing values in boolean:-

csv.isnull()        #True/False

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [28]:
#finding missing values by columns:-

csv.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [29]:
#Drop Row with missing values-

dropped=csv.dropna()  #Drop the (NaN) Rows.
dropped

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [30]:
#Fill Missing Vaues (using fillna):-

# 1-> Replacing NaN values with 0

filled=csv.fillna(0)   #Replace all NaN values with 0
filled

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,0,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,0,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,0,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,0,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,0.0,1,2,W./C. 6607,23.4500,0,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,0,Q

In [33]:
# Fill with different values in column

custom_csv = csv.fillna({
    'Age': csv['Age'].mean(),     #Replace all the NaN values in Age( with average of age).
    'Cabin': 'Unknown',           #Replace all the NaN values in Cabin with 'Unknown'.
    'Fare': csv['Fare'].median()  #Replace all the NaN values in Fare( with median of Fare).
})
custom_csv

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,Unknown,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,Unknown,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,Unknown,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,Unknown,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,Unknown,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,Unknown,Q

In [38]:
# Forward fill-

forward_filled=csv.fillna(method='ffill')  #It replace the NaN values with forward value
forward_filled

C:\Users\Prince Chandravat\AppData\Local\Temp\ipykernel_5040\1346205509.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  forward_filled=csv.fillna(method='ffill')  #It replace the NaN values with forward value

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,C85,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,C123,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,C50,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,19.0,1,2,W./C. 6607,23.4500,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,C148,Q

In [43]:
# Backward fill-

backward_filled=csv.fillna(method='bfill')  #It replace the NaN values with backward value

backward_filled

C:\Users\Prince Chandravat\AppData\Local\Temp\ipykernel_5040\2687483315.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  backward_filled=csv.fillna(method='bfill')  #It replace the NaN values with backward value

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,C85,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,C123,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,B42,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,26.0,1,2,W./C. 6607,23.4500,C148,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [35]:
#Now save this data to a new csv with cleaned data-

custom_csv.to_csv("titanic_cleaned.csv",index=False)     #Cretating a new csv file Without Index.

# 2)-Filtering/Selecting Rows-

In [44]:
#Reading a ipl csv-

ipl=pd.read_csv("C:\\Users\\Prince Chandravat\\Downloads\\ipl-matches.csv")  #Ipl data
ipl

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [60]:
#first 2 matches:-

ipl.tail(2)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [46]:
ipl.describe()

                 ID      Margin
count  9.500000e+02  932.000000
mean   8.304852e+05   17.056867
std    3.375678e+05   21.633109
min    3.359820e+05    1.000000
25%    5.012612e+05    6.000000
50%    8.297380e+05    8.000000
75%    1.175372e+06   19.000000
max    1.312200e+06  146.000000

# Boolean Filtering-

In [50]:
# 50 or above Margin Matches:-

above_50_Margin=ipl[ipl['Margin']>50.0]  #Filtering data above or equalt to 50 margin.
above_50_Margin

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
13,1304107,Pune,2022-05-14,2022,61,Kolkata Knight Riders,Sunrisers Hyderabad,"Maharashtra Cricket Association Stadium, Pune",Kolkata Knight Riders,bat,N,Kolkata Knight Riders,Runs,54.0,NaN,AD Russell,"['VR Iyer', 'AM Rahane', 'N Rana', 'SS Iyer', ...","['Abhishek Sharma', 'KS Williamson', 'RA Tripa...",AK Chaudhary,KN Ananthapadmanabhan
14,1304106,Mumbai,2022-05-13,2022,60,Punjab Kings,Royal Challengers Bangalore,"Brabourne Stadium, Mumbai",Royal Challengers Bangalore,field,N,Punjab Kings,Runs,54.0,NaN,JM Bairstow,"['JM Bairstow', 'S Dhawan', 'PBB Rajapaksa', '...","['V Kohli', 'F du Plessis', 'RM Patidar', 'MK ...",J Madanagopal,N Pandit
17,1304103,Pune,2022-05-10,2022,57,Gujarat Titans,Lucknow Super Giants,"Maharashtra Cricket Association Stadium, Pune",Gujarat Titans,bat,N,Gujarat Titans,Runs,62.0,NaN,Shubman Gill,"['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...","['Q de Kock', 'KL Rahul', 'DJ Hooda', 'KS Shar...",KN Ananthapadmanabhan,MA Gough
18,1304102,Navi Mumbai,2022-05-09,2022,56,Kolkata Knight Riders,Mumbai Indians,"Dr DY Patil Sports Academy, Mumbai",Mumbai Indians,field,N,Kolkata Knight Riders,Runs,52.0,NaN,JJ Bumrah,"['VR Iyer', 'AM Rahane', 'N Rana', 'SS Iyer', ...","['RG Sharma', 'Ishan Kishan', 'Tilak Varma', '...",CB Gaffaney,GR Sadashiv Iyer
19,1304101,Navi Mumbai,2022-05-08,2022,55,Chennai Super Kings,Delhi Capitals,"Dr DY Patil Sports Academy, Mumbai",Delhi Capitals,field,N,Chennai Super Kings,Runs,91.0,NaN,DP Conway,"['RD Gaikwad', 'DP Conway', 'S Dube', 'AT Rayu...","['DA Warner', 'KS Bharat', 'MR Marsh', 'RR Pan...",Nitin Menon,R Pandit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
890,392182,Cape Town,2009-04-18,2009,2,Royal Challengers Bangalore,Rajasthan Royals,Newlands,Royal Challengers Bangalore,bat,N,Royal Challengers Bangalore,Runs,75.0,NaN,R Dravid,"['JD Ryder', 'RV Uthappa', 'LRPL Taylor', 'KP ...","['GC Smith', 'SA Asnodkar', 'NK Patel', 'T Hen...",BR Doctrove,RB Tiffin
894,336038,Mumbai,2008-05-30,2007/08,Semi Final,Delhi Daredevils,Rajasthan Royals,Wankhede Stadium,Delhi Daredevils,field,N,Rajasthan Royals,Runs,105.0,NaN,SR Watson,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['GC Smith', 'SA Asnodkar', 'Sohail Tanvir', '...",BF Bowden,RE Koertzen
911,336023,Jaipur,2008-05-17,2007/08,39,Rajasthan Royals,Royal Challengers Bangalore,Sawai Mansingh Stadium,Royal Challengers Bangalore,field,N,Rajasthan Royals,Runs,65.0,NaN,GC Smith,"['GC Smith', 'SA Asnodkar', 'SR Watson', 'YK P...","['J Arunkumar', 'V Kohli', 'Misbah-ul-Haq', 'J...",BF Bowden,SL Shastri
940,335991,Chandigarh,2008-04-25,2007/08,10,Kings XI Punjab,Mumbai Indians,"Punjab Cricket Association Stadium, Mohali",Mumbai Indians,field,N,Kings XI Punjab,Runs,66.0,NaN,KC Sangakkara,"['K Goel', 'IK Pathan', 'KC Sangakkara', 'Yuvr...","['L Ronchi', 'ST Jayasuriya', 'RV Uthappa', 'D...",Aleem Dar,AM Saheba
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [57]:
# another example of Boolean filtering -

# only Royal Challengers Bangalore matches-

rcb_matches=ipl[(ipl['Team1']=='Royal Challengers Bangalore') | (ipl['Team2']=='Royal Challengers Bangalore')]
rcb_matches

#here all royal challengers bangalore matches since 2008-

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
7,1304113,Mumbai,2022-05-19,2022,67,Gujarat Titans,Royal Challengers Bangalore,"Wankhede Stadium, Mumbai",Gujarat Titans,bat,N,Royal Challengers Bangalore,Wickets,8.0,NaN,V Kohli,"['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...","['V Kohli', 'F du Plessis', 'GJ Maxwell', 'KD ...",KN Ananthapadmanabhan,GR Sadashiv Iyer
14,1304106,Mumbai,2022-05-13,2022,60,Punjab Kings,Royal Challengers Bangalore,"Brabourne Stadium, Mumbai",Royal Challengers Bangalore,field,N,Punjab Kings,Runs,54.0,NaN,JM Bairstow,"['JM Bairstow', 'S Dhawan', 'PBB Rajapaksa', '...","['V Kohli', 'F du Plessis', 'RM Patidar', 'MK ...",J Madanagopal,N Pandit
20,1304100,Mumbai,2022-05-08,2022,54,Royal Challengers Bangalore,Sunrisers Hyderabad,"Wankhede Stadium, Mumbai",Royal Challengers Bangalore,bat,N,Royal Challengers Bangalore,Runs,67.0,NaN,PWH de Silva,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Abhishek Sharma', 'KS Williamson', 'RA Tripa...",BNJ Oxenford,N Pandit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
933,335998,Delhi,2008-04-30,2007/08,17,Delhi Daredevils,Royal Challengers Bangalore,Feroz Shah Kotla,Royal Challengers Bangalore,field,N,Delhi Daredevils,Runs,10.0,NaN,GD McGrath,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'Shoaib ...","['P Kumar', 'W Jaffer', 'LRPL Taylor', 'JH Kal...",Aleem Dar,I Shivram
935,335996,Bangalore,2008-04-28,2007/08,15,Royal Challengers Bangalore,Chennai Super Kings,M Chinnaswamy Stadium,Chennai Super Kings,bat,N,Chennai Super Kings,Runs,13.0,NaN,MS Dhoni,"['B Chipli', 'W Jaffer', 'LRPL Taylor', 'JH Ka...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'SK Ra...",BR Doctrove,RB Tiffin
939,335992,Bangalore,2008-04-26,2007/08,12,Royal Challengers Bangalore,Rajasthan Royals,M Chinnaswamy Stadium,Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,SR Watson,"['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...","['GC Smith', 'M Rawat', 'YK Pathan', 'SR Watso...",MR Benson,IL Howell
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [59]:
#matches are playing in mumbai (venue) :-

matches_in_mumbai=ipl[(ipl['City']=='Mumbai') | (ipl['City']=='Navi Mumbai')]

#All matches which playing in mumbai city (including Navi mumbai):-

matches_in_mumbai

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
5,1304115,Mumbai,2022-05-21,2022,69,Delhi Capitals,Mumbai Indians,"Wankhede Stadium, Mumbai",Mumbai Indians,field,N,Mumbai Indians,Wickets,5.0,NaN,JJ Bumrah,"['PP Shaw', 'DA Warner', 'MR Marsh', 'RR Pant'...","['Ishan Kishan', 'RG Sharma', 'D Brevis', 'Til...",Nitin Menon,Tapan Sharma
6,1304114,Mumbai,2022-05-20,2022,68,Chennai Super Kings,Rajasthan Royals,"Brabourne Stadium, Mumbai",Chennai Super Kings,bat,N,Rajasthan Royals,Wickets,5.0,NaN,R Ashwin,"['RD Gaikwad', 'DP Conway', 'MM Ali', 'N Jagad...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,NA Patwardhan
7,1304113,Mumbai,2022-05-19,2022,67,Gujarat Titans,Royal Challengers Bangalore,"Wankhede Stadium, Mumbai",Gujarat Titans,bat,N,Royal Challengers Bangalore,Wickets,8.0,NaN,V Kohli,"['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...","['V Kohli', 'F du Plessis', 'GJ Maxwell', 'KD ...",KN Ananthapadmanabhan,GR Sadashiv Iyer
8,1304112,Navi Mumbai,2022-05-18,2022,66,Lucknow Super Giants,Kolkata Knight Riders,"Dr DY Patil Sports Academy, Mumbai",Lucknow Super Giants,bat,N,Lucknow Super Giants,Runs,2.0,NaN,Q de Kock,"['Q de Kock', 'KL Rahul', 'E Lewis', 'DJ Hooda...","['VR Iyer', 'A Tomar', 'N Rana', 'SS Iyer', 'S...",R Pandit,YC Barde
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
914,336018,Mumbai,2008-05-14,2007/08,36,Mumbai Indians,Chennai Super Kings,Wankhede Stadium,Mumbai Indians,field,N,Mumbai Indians,Wickets,9.0,NaN,ST Jayasuriya,"['ST Jayasuriya', 'SR Tendulkar', 'RV Uthappa'...","['S Vidyut', 'SP Fleming', 'SK Raina', 'S Badr...",BR Doctrove,AM Saheba
923,336008,Mumbai,2008-05-07,2007/08,27,Mumbai Indians,Rajasthan Royals,Dr DY Patil Sports Academy,Mumbai Indians,field,N,Mumbai Indians,Wickets,7.0,NaN,A Nehra,"['YV Takawale', 'ST Jayasuriya', 'RV Uthappa',...","['GC Smith', 'SA Asnodkar', 'YK Pathan', 'SR W...",DJ Harper,RE Koertzen
927,336004,Mumbai,2008-05-04,2007/08,23,Mumbai Indians,Delhi Daredevils,Dr DY Patil Sports Academy,Delhi Daredevils,field,N,Mumbai Indians,Runs,29.0,NaN,SM Pollock,"['YV Takawale', 'ST Jayasuriya', 'DJ Thornely'...","['G Gambhir', 'V Sehwag', 'S Dhawan', 'AB de V...",IL Howell,RE Koertzen
937,335994,Mumbai,2008-04-27,2007/08,14,Mumbai Indians,Deccan Chargers,Dr DY Patil Sports Academy,Deccan Chargers,field,N,Deccan Chargers,Wickets,10.0,NaN,AC Gilchrist,"['L Ronchi', 'ST Jayasuriya', 'AM Rahane', 'RV...","['AC Gilchrist', 'VVS Laxman', 'A Symonds', 'R...",Asad Rauf,SL Shastri
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper

In [67]:
#Final matches after 2019

final_after_2019=ipl[(ipl['Date']>'2020-01-01') & (ipl['MatchNumber']=='Final')] 
final_after_2019

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
74,1254117,Dubai,2021-10-15,2021,Final,Chennai Super Kings,Kolkata Knight Riders,Dubai International Cricket Stadium,Kolkata Knight Riders,field,N,Chennai Super Kings,Runs,27.0,NaN,F du Plessis,"['RD Gaikwad', 'F du Plessis', 'RV Uthappa', '...","['Shubman Gill', 'VR Iyer', 'N Rana', 'SP Nari...",Nitin Menon,RK Illingworth
134,1237181,NaN,2020-11-10,2020/21,Final,Delhi Capitals,Mumbai Indians,Dubai International Cricket Stadium,Delhi Capitals,bat,N,Mumbai Indians,Wickets,5.0,NaN,TA Boult,"['MP Stoinis', 'S Dhawan', 'AM Rahane', 'SS Iy...","['RG Sharma', 'Q de Kock', 'SA Yadav', 'Ishan ...",CB Gaffaney,Nitin Menon

In [70]:
#filtering With Strings-

virat_kohli=ipl[ipl['Player_of_Match']=='V Kohli']

#When Virat kohli Man of the MAtch-
virat_kohli

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
7,1304113,Mumbai,2022-05-19,2022,67,Gujarat Titans,Royal Challengers Bangalore,"Wankhede Stadium, Mumbai",Gujarat Titans,bat,N,Royal Challengers Bangalore,Wickets,8.0,NaN,V Kohli,"['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...","['V Kohli', 'F du Plessis', 'GJ Maxwell', 'KD ...",KN Ananthapadmanabhan,GR Sadashiv Iyer
170,1216525,NaN,2020-10-10,2020/21,25,Royal Challengers Bangalore,Chennai Super Kings,Dubai International Cricket Stadium,Royal Challengers Bangalore,bat,N,Royal Challengers Bangalore,Runs,37.0,NaN,V Kohli,"['D Padikkal', 'AJ Finch', 'V Kohli', 'AB de V...","['SR Watson', 'F du Plessis', 'AT Rayudu', 'N ...",AK Chaudhary,PR Reiffel
219,1178410,Kolkata,2019-04-19,2019,35,Royal Challengers Bangalore,Kolkata Knight Riders,Eden Gardens,Kolkata Knight Riders,field,N,Royal Challengers Bangalore,Runs,10.0,NaN,V Kohli,"['PA Patel', 'V Kohli', 'AD Nath', 'MM Ali', '...","['CA Lynn', 'SP Narine', 'Shubman Gill', 'RV U...",IJ Gould,Nitin Menon
377,981011,Raipur,2016-05-22,2016,56,Delhi Daredevils,Royal Challengers Bangalore,Shaheed Veer Narayan Singh International Stadium,Royal Challengers Bangalore,field,N,Royal Challengers Bangalore,Wickets,6.0,NaN,V Kohli,"['Q de Kock', 'RR Pant', 'KK Nair', 'SV Samson...","['CH Gayle', 'V Kohli', 'AB de Villiers', 'KL ...",A Nand Kishore,BNJ Oxenford
383,980999,Bangalore,2016-05-18,2016,50,Royal Challengers Bangalore,Kings XI Punjab,M Chinnaswamy Stadium,Kings XI Punjab,field,N,Royal Challengers Bangalore,Runs,82.0,D/L,V Kohli,"['CH Gayle', 'V Kohli', 'AB de Villiers', 'KL ...","['M Vijay', 'HM Amla', 'WP Saha', 'DA Miller',...",KN Ananthapadmanabhan,M Erasmus
385,980995,Kolkata,2016-05-16,2016,48,Kolkata Knight Riders,Royal Challengers Bangalore,Eden Gardens,Royal Challengers Bangalore,field,N,Royal Challengers Bangalore,Wickets,9.0,NaN,V Kohli,"['RV Uthappa', 'G Gambhir', 'MK Pandey', 'YK P...","['CH Gayle', 'V Kohli', 'AB de Villiers', 'SR ...",CB Gaffaney,A Nand Kishore
398,980969,Bangalore,2016-05-07,2016,35,Royal Challengers Bangalore,Rising Pune Supergiants,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Royal Challengers Bangalore,Wickets,7.0,NaN,V Kohli,"['V Kohli', 'KL Rahul', 'AB de Villiers', 'SR ...","['AM Rahane', 'UT Khawaja', 'SS Tiwary', 'MS D...",CB Gaffaney,BNJ Oxenford
414,980937,Rajkot,2016-04-24,2016,19,Gujarat Lions,Royal Challengers Bangalore,Saurashtra Cricket Association Stadium,Royal Challengers Bangalore,bat,N,Gujarat Lions,Wickets,6.0,NaN,V Kohli,"['DR Smith', 'BB McCullum', 'SK Raina', 'KD Ka...","['V Kohli', 'SR Watson', 'AB de Villiers', 'KL...",K Bharatan,BNJ Oxenford
441,829807,Hyderabad,2015-05-15,2015,52,Sunrisers Hyderabad,Royal Challengers Bangalore,"Rajiv Gandhi International Stadium, Uppal",Sunrisers Hyderabad,bat,N,Royal Challengers Bangalore,Wickets,6.0,D/L,V Kohli,"['DA Warner', 'S Dhawan', 'MC Henriques', 'EJG...","['CH Gayle', 'V Kohli', 'AB de Villiers', 'Man...",AK Chaudhary,HDPK Dharmasena
558,598068,Bangalore,2013-05-18,2013,70,Royal Challengers Bangalore,Chennai Super Kings,M Chinnaswamy Stadium,Chennai Super Kings,field,N,Royal Challengers Bangalore,Runs,24.0,NaN,V Kohli,"['V Kohli', 'CH Gayle', 'AB de Villiers', 'MC ...","['MEK Hussey', 'M Vijay', 'SK Raina', 'DJ Brav...",C Shamshuddin,RJ Tucker
608,598017,Bangalore,2013-04-16,2013,21,Royal Challengers Bangalore,Delhi Daredevils,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,Y,Royal Challengers Bangalore,SuperOver,NaN,NaN,V Kohli,"['CH Gayle', 'KL Rahul', 'V Kohli', 'AB de Vil...","['DA Warner', 'V Sehwag', 'MC Juneja', 'DPMD J...",M Erasmus,VA Kulkarni
618,598048,Bangalore,2013-04-09,2013,9,Royal Challengers Bangalore,Sunrisers Hyderabad,M Chinnaswamy Stadium,Sunrisers Hyderabad,bat,N,Royal Challengers Bangalore,Wickets,7.0,NaN,V Kohli,"['MA Agarwal', 'CH Gayle', 'V Kohli', 'AB de V...","['PA Reddy', 'PA Patel', 'KC Sangakkara', 'CL ...",S Ravi,SJA Taufel
741,501232,Bangalore,2011-04-29,2011,35,Royal Challengers Bangalore,Pune Warriors,M Chinnaswamy Stadium,Pune Warriors,field,N,Royal Challengers Bangalore,Runs,26.0,NaN,V Kohli,"['CH Gayle', 'TM Dilshan', 'V Kohli', 'AB de V...","['JD Ryder', 'TD Paine', 'MK Pandey', 'Yuvraj ...",Aleem Dar,SS Hazare
746,501227,Delhi,2011-04-26,2011,30,Delhi Daredevils,Royal Challengers Bangalore,Feroz Shah Kotla,Royal Challengers Bangalore,field,N,Royal Challengers Bangalore,Wickets,3.0,NaN,V Kohli,"['DA Warner', 'V Sehwag', 'JR Hopes', 'MS Wade...","['CH Gayle', 'TM Dilshan', 'V Kohli', 'AB de V...",S Asnani,RJ Tucker

In [89]:
# Filtering Final matches with WinningTeam,Season,Venue,Team1Players,Team2Players:-
    
ipl[ipl['MatchNumber']=='Final'][['WinningTeam','Season','Venue','Team1Players','Team2Players']]

,WinningTeam,Season,Venue,Team1Players,Team2Players
0,Gujarat Titans,2022,"Narendra Modi Stadium, Ahmedabad","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan..."
74,Chennai Super Kings,2021,Dubai International Cricket Stadium,"['RD Gaikwad', 'F du Plessis', 'RV Uthappa', '...","['Shubman Gill', 'VR Iyer', 'N Rana', 'SP Nari..."
134,Mumbai Indians,2020/21,Dubai International Cricket Stadium,"['MP Stoinis', 'S Dhawan', 'AM Rahane', 'SS Iy...","['RG Sharma', 'Q de Kock', 'SA Yadav', 'Ishan ..."
194,Mumbai Indians,2019,Rajiv Gandhi International Stadium,"['Q de Kock', 'RG Sharma', 'SA Yadav', 'Ishan ...","['F du Plessis', 'SR Watson', 'SK Raina', 'AT ..."
254,Chennai Super Kings,2018,Wankhede Stadium,"['SP Goswami', 'S Dhawan', 'KS Williamson', 'S...","['SR Watson', 'F du Plessis', 'SK Raina', 'AT ..."
314,Mumbai Indians,2017,"Rajiv Gandhi International Stadium, Uppal","['LMP Simmons', 'PA Patel', 'AT Rayudu', 'RG S...","['AM Rahane', 'RA Tripathi', 'SPD Smith', 'MS ..."
373,Sunrisers Hyderabad,2016,M Chinnaswamy Stadium,"['CH Gayle', 'V Kohli', 'AB de Villiers', 'KL ...","['DA Warner', 'S Dhawan', 'MC Henriques', 'Yuv..."
433,Mumbai Indians,2015,Eden Gardens,"['LMP Simmons', 'PA Patel', 'RG Sharma', 'KA P...","['DR Smith', 'MEK Hussey', 'SK Raina', 'MS Dho..."
492,Kolkata Knight Riders,2014,M Chinnaswamy Stadium,"['RV Uthappa', 'G Gambhir', 'MK Pandey', 'YK P...","['V Sehwag', 'M Vohra', 'GJ Bailey', 'WP Saha'..."
552,Mumbai Indians,2013,Eden Gardens,"['MEK Hussey', 'M Vijay', 'SK Raina', 'S Badri...","['DR Smith', 'AP Tare', 'KD Karthik', 'RG Shar..."
628,Kolkata Knight Riders,2012,"MA Chidambaram Stadium, Chepauk","['MS Bisla', 'G Gambhir', 'JH Kallis', 'LR Shu...","['MEK Hussey', 'M Vijay', 'SK Raina', 'MS Dhon..."
702,Chennai Super Kings,2011,"MA Chidambaram Stadium, Chepauk","['MEK Hussey', 'M Vijay', 'MS Dhoni', 'SK Rain...","['MA Agarwal', 'CH Gayle', 'V Kohli', 'AB de V..."
775,Chennai Super Kings,2009/10,Dr DY Patil Sports Academy,"['M Vijay', 'ML Hayden', 'SK Raina', 'S Badrin...","['S Dhawan', 'SR Tendulkar', 'AM Nayar', 'Harb..."
835,Deccan Chargers,2009,New Wanderers Stadium,"['JH Kallis', 'MK Pandey', 'RE van der Merwe',...","['AC Gilchrist', 'HH Gibbs', 'TL Suman', 'A Sy..."
892,Rajasthan Royals,2007/08,Dr DY Patil Sports Academy,"['PA Patel', 'S Vidyut', 'SK Raina', 'JA Morke...","['NK Patel', 'SA Asnodkar', 'Kamran Akmal', 'S..."

In [105]:
#Chennai Winnings in final-

ipl[(ipl['MatchNumber']=='Final') & (ipl['WinningTeam']=='Chennai Super Kings')]

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
74,1254117,Dubai,2021-10-15,2021,Final,Chennai Super Kings,Kolkata Knight Riders,Dubai International Cricket Stadium,Kolkata Knight Riders,field,N,Chennai Super Kings,Runs,27.0,NaN,F du Plessis,"['RD Gaikwad', 'F du Plessis', 'RV Uthappa', '...","['Shubman Gill', 'VR Iyer', 'N Rana', 'SP Nari...",Nitin Menon,RK Illingworth
254,1136620,Mumbai,2018-05-27,2018,Final,Sunrisers Hyderabad,Chennai Super Kings,Wankhede Stadium,Chennai Super Kings,field,N,Chennai Super Kings,Wickets,8.0,NaN,SR Watson,"['SP Goswami', 'S Dhawan', 'KS Williamson', 'S...","['SR Watson', 'F du Plessis', 'SK Raina', 'AT ...",M Erasmus,S Ravi
702,501271,Chennai,2011-05-28,2011,Final,Chennai Super Kings,Royal Challengers Bangalore,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,58.0,NaN,M Vijay,"['MEK Hussey', 'M Vijay', 'MS Dhoni', 'SK Rain...","['MA Agarwal', 'CH Gayle', 'V Kohli', 'AB de V...",Asad Rauf,SJA Taufel
775,419165,Mumbai,2010-04-25,2009/10,Final,Chennai Super Kings,Mumbai Indians,Dr DY Patil Sports Academy,Chennai Super Kings,bat,N,Chennai Super Kings,Runs,22.0,NaN,SK Raina,"['M Vijay', 'ML Hayden', 'SK Raina', 'S Badrin...","['S Dhawan', 'SR Tendulkar', 'AM Nayar', 'Harb...",RE Koertzen,SJA Taufel

In [102]:
ipl[['Team1','Team2','WinningTeam']]

,Team1,Team2,WinningTeam
0,Rajasthan Royals,Gujarat Titans,Gujarat Titans
1,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals
2,Royal Challengers Bangalore,Lucknow Super Giants,Royal Challengers Bangalore
3,Rajasthan Royals,Gujarat Titans,Gujarat Titans
4,Sunrisers Hyderabad,Punjab Kings,Punjab Kings
...,...,...,...
945,Kolkata Knight Riders,Deccan Chargers,Kolkata Knight Riders
946,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore
947,Delhi Daredevils,Rajasthan Royals,Delhi Daredevils
948,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings
949,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders

In [106]:
#Indexing & Slicing:-

ipl.iloc[0:5]         #0 to 5 columns.

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [123]:
ipl.iloc[:7]

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
5,1304115,Mumbai,2022-05-21,2022,69,Delhi Capitals,Mumbai Indians,"Wankhede Stadium, Mumbai",Mumbai Indians,field,N,Mumbai Indians,Wickets,5.0,NaN,JJ Bumrah,"['PP Shaw', 'DA Warner', 'MR Marsh', 'RR Pant'...","['Ishan Kishan', 'RG Sharma', 'D Brevis', 'Til...",Nitin Menon,Tapan Sharma
6,1304114,Mumbai,2022-05-20,2022,68,Chennai Super Kings,Rajasthan Royals,"Brabourne Stadium, Mumbai",Chennai Super Kings,bat,N,Rajasthan Royals,Wickets,5.0,NaN,R Ashwin,"['RD Gaikwad', 'DP Conway', 'MM Ali', 'N Jagad...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,NA Patwardhan

# 3)- Adding/Dropping renaming:-

In [6]:
# Creating a DataFrame-

data={'First Name':['Prince','Hritik','Vibhor','Mayank','Keshav'],
      'Last Name':['Chandravat','Roshan','Sharma','Rana','Yadav'],
      'City': ['Delhi','Mumbai','Hyderabad','Gurgaon','Jaipur']}
df=pd.DataFrame(data)
df

  First Name   Last Name       City
0     Prince  Chandravat      Delhi
1     Hritik      Roshan     Mumbai
2     Vibhor      Sharma  Hyderabad
3     Mayank        Rana    Gurgaon
4     Keshav       Yadav     Jaipur

In [7]:
#Adding age column-

df['Age'] = [20, 21, 22, 21, 20]
df

  First Name   Last Name       City  Age
0     Prince  Chandravat      Delhi   20
1     Hritik      Roshan     Mumbai   21
2     Vibhor      Sharma  Hyderabad   22
3     Mayank        Rana    Gurgaon   21
4     Keshav       Yadav     Jaipur   20

In [40]:
#Deleting first name and last name:-

df.drop(columns=['First Name','Last Name'])

        City  Age
0      Delhi   20
1     Mumbai   21
2  Hyderabad   22
3    Gurgaon   21
4     Jaipur   20

In [ ]:
#Adding Serial.No 
df.insert(0,'S.no',[1,2,3,4,5])

In [70]:
df

   S.no First Name   Last Name       City  Age
0     1     Prince  Chandravat      Delhi   20
1     2     Hritik      Roshan     Mumbai   21
2     3     Vibhor      Sharma  Hyderabad   22
3     4     Mayank        Rana    Gurgaon   21
4     5     Keshav       Yadav     Jaipur   20

In [73]:
#Creating a dataframe-

students_marks={'Students': ['Ritik','Vibhor','Pawan','Farhan','keshav','Gautam','Saurabh','Neeraj','Nitish','Deepak'],
                'Marks': [420,435,443,329,339,328,433,484,442,329],
                'city': ['Delhi','Hyderabad','Kolkata','Mohali','Jaipur','Kota','Meerut','Ambikapur','Delhi','bangalore']}
df=pd.DataFrame(students_marks)
df

  Students  Marks       city
0    Ritik    420      Delhi
1   Vibhor    435  Hyderabad
2    Pawan    443    Kolkata
3   Farhan    329     Mohali
4   keshav    339     Jaipur
5   Gautam    328       Kota
6  Saurabh    433     Meerut
7   Neeraj    484  Ambikapur
8   Nitish    442      Delhi
9   Deepak    329  bangalore

In [76]:
# reading a csv

csv=pd.read_csv("C:\\Users\\Prince Chandravat\\Downloads\\Customer Call List.csv")
csv.head()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Unnamed: 8,Unnamed: 9
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True,NaN,NaN
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False,NaN,NaN
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True,NaN,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,NaN,NaN
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True,NaN,NaN

In [89]:
#Renaming-

# Address to Customer_Address  , Unnamed: 8 to None,  unnamed: 9 to None:-

rename=csv.rename(columns={'Address':'Customer_Address','Unnamed: 8':'None','Unnamed: 9':'None'})
rename.head(1)

,CustomerID,First_Name,Last_Name,Phone_Number,Customer_Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,None,None
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True,NaN,NaN

# Boolean masks and Advance filtering:-

In [127]:
ipl=pd.read_csv("C:\\Users\\Prince Chandravat\\Downloads\\ipl-matches.csv")
ipl.head(1)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon

#Filtering-

In [133]:
#Find all the final Winners-

final_winners=ipl[ipl['MatchNumber']=='Final'][['Season','WinningTeam']]   
final_winners

      Season            WinningTeam
0       2022         Gujarat Titans
74      2021    Chennai Super Kings
134  2020/21         Mumbai Indians
194     2019         Mumbai Indians
254     2018    Chennai Super Kings
314     2017         Mumbai Indians
373     2016    Sunrisers Hyderabad
433     2015         Mumbai Indians
492     2014  Kolkata Knight Riders
552     2013         Mumbai Indians
628     2012  Kolkata Knight Riders
702     2011    Chennai Super Kings
775  2009/10    Chennai Super Kings
835     2009        Deccan Chargers
892  2007/08       Rajasthan Royals

In [134]:
#Find all matches where Royal Challengers Bangalore played-
rcb_matches = ipl[(ipl['Team1'] == 'Royal Challengers Bangalore') | (ipl['Team2'] == 'Royal Challengers Bangalore')]

#print only rcb matches.
rcb_matches

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
7,1304113,Mumbai,2022-05-19,2022,67,Gujarat Titans,Royal Challengers Bangalore,"Wankhede Stadium, Mumbai",Gujarat Titans,bat,N,Royal Challengers Bangalore,Wickets,8.0,NaN,V Kohli,"['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...","['V Kohli', 'F du Plessis', 'GJ Maxwell', 'KD ...",KN Ananthapadmanabhan,GR Sadashiv Iyer
14,1304106,Mumbai,2022-05-13,2022,60,Punjab Kings,Royal Challengers Bangalore,"Brabourne Stadium, Mumbai",Royal Challengers Bangalore,field,N,Punjab Kings,Runs,54.0,NaN,JM Bairstow,"['JM Bairstow', 'S Dhawan', 'PBB Rajapaksa', '...","['V Kohli', 'F du Plessis', 'RM Patidar', 'MK ...",J Madanagopal,N Pandit
20,1304100,Mumbai,2022-05-08,2022,54,Royal Challengers Bangalore,Sunrisers Hyderabad,"Wankhede Stadium, Mumbai",Royal Challengers Bangalore,bat,N,Royal Challengers Bangalore,Runs,67.0,NaN,PWH de Silva,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Abhishek Sharma', 'KS Williamson', 'RA Tripa...",BNJ Oxenford,N Pandit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
933,335998,Delhi,2008-04-30,2007/08,17,Delhi Daredevils,Royal Challengers Bangalore,Feroz Shah Kotla,Royal Challengers Bangalore,field,N,Delhi Daredevils,Runs,10.0,NaN,GD McGrath,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'Shoaib ...","['P Kumar', 'W Jaffer', 'LRPL Taylor', 'JH Kal...",Aleem Dar,I Shivram
935,335996,Bangalore,2008-04-28,2007/08,15,Royal Challengers Bangalore,Chennai Super Kings,M Chinnaswamy Stadium,Chennai Super Kings,bat,N,Chennai Super Kings,Runs,13.0,NaN,MS Dhoni,"['B Chipli', 'W Jaffer', 'LRPL Taylor', 'JH Ka...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'SK Ra...",BR Doctrove,RB Tiffin
939,335992,Bangalore,2008-04-26,2007/08,12,Royal Challengers Bangalore,Rajasthan Royals,M Chinnaswamy Stadium,Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,SR Watson,"['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...","['GC Smith', 'M Rawat', 'YK Pathan', 'SR Watso...",MR Benson,IL Howell
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [138]:
# How many matchess has csk won in kolkata-

csk_in_kolkata=ipl[(ipl['City']=='Kolkata') & (ipl['WinningTeam']=='Chennai Super Kings')]   #filtering only csk winning matches in kolkata
csk_in_kolkata

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
224,1178404,Kolkata,2019-04-14,2019,29,Kolkata Knight Riders,Chennai Super Kings,Eden Gardens,Chennai Super Kings,field,N,Chennai Super Kings,Wickets,5.0,NaN,Imran Tahir,"['CA Lynn', 'SP Narine', 'N Rana', 'RV Uthappa...","['SR Watson', 'F du Plessis', 'SK Raina', 'AT ...",CK Nandan,RJ Tucker
602,598022,Kolkata,2013-04-20,2013,26,Kolkata Knight Riders,Chennai Super Kings,Eden Gardens,Kolkata Knight Riders,bat,N,Chennai Super Kings,Wickets,4.0,NaN,RA Jadeja,"['G Gambhir', 'YK Pathan', 'JH Kallis', 'EJG M...","['MEK Hussey', 'R Ashwin', 'M Vijay', 'SK Rain...",Asad Rauf,AK Chaudhary
641,548368,Kolkata,2012-05-14,2012,63,Kolkata Knight Riders,Chennai Super Kings,Eden Gardens,Chennai Super Kings,field,N,Chennai Super Kings,Wickets,5.0,NaN,MEK Hussey,"['G Gambhir', 'BB McCullum', 'JH Kallis', 'MK ...","['MEK Hussey', 'M Vijay', 'SK Raina', 'F du Pl...",JD Cloete,SJA Taufel
827,419113,Kolkata,2010-03-16,2009/10,8,Kolkata Knight Riders,Chennai Super Kings,Eden Gardens,Chennai Super Kings,bat,N,Chennai Super Kings,Runs,55.0,NaN,MS Dhoni,"['BJ Hodge', 'MK Tiwary', 'SC Ganguly', 'WP Sa...","['M Vijay', 'ML Hayden', 'SK Raina', 'S Badrin...",HDPK Dharmasena,AM Saheba
908,336025,Kolkata,2008-05-18,2007/08,41,Kolkata Knight Riders,Chennai Super Kings,Eden Gardens,Kolkata Knight Riders,bat,N,Chennai Super Kings,Runs,3.0,D/L,M Ntini,"['Salman Butt', 'Mohammad Hafeez', 'SC Ganguly...","['PA Patel', 'SP Fleming', 'S Vidyut', 'SK Rai...",Asad Rauf,K Hariharan

In [146]:
# Toss winner is the match winner in percentage-

(ipl[ipl['TossWinner']==ipl['WinningTeam']].shape[0]/ipl.shape[0])*100  #use .shape for total matches of winning and calculate percentage.

51.473684210526315

In [149]:
#reading a movie csv file for filtering and operating boolean functions:-

movies=pd.read_csv("C:\\Users\\Prince Chandravat\\Downloads\\movies.csv")
movies.sample(1)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
613,Sixteen (2013 Indian film),tt2976172,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Sixteen_(2013_In...,Sixteen,Sixteen,0,2013,138,Drama|Romance|Thriller,6.3,1581,Welcome to sixteen's world. A world where grow...,Welcome to sixteen's world. A world where grow...,NaN,Wamiqa Gabbi|Izabelle Leite|Mehak Manwani|High...,NaN,12 July 2013 (India)

In [171]:
# Show all movies with an IMDb rating greater than 8.0 and votes>10000

movie=movies[(movies['imdb_rating']>8.0) & (movies['imdb_votes']>10000)]    #all the movies above 8.0 imdb rating with 10000 above rating.
print("Total no. of movies with 8.0 above ratings and votes over 10000 is==>", movie.shape[0])
movie

Total no. of movies with 8.0 above ratings and votes over 10000 is==> 43

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
11,Gully Boy,tt2395469,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gully_Boy,Gully Boy,Gully Boy,0,2019,153,Drama|Music,8.2,22440,"Gully Boy is a film about a 22-year-old boy ""M...",A coming-of-age story based on the lives of st...,Apna Time Aayega!,Ranveer Singh|Alia Bhatt|Siddhant Chaturvedi|V...,6 wins & 3 nominations,14 February 2019 (USA)
37,Article 15 (film),tt10324144,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Article_15_(film),Article 15,Article 15,0,2019,130,Crime|Drama,8.3,13417,In the rural heartlands of India an upright p...,In the rural heartlands of India an upright p...,Farq Bahut Kar Liya| Ab Farq Laayenge.,Ayushmann Khurrana|Nassar|Manoj Pahwa|Kumud Mi...,1 win,28 June 2019 (USA)
40,Super 30 (film),tt7485048,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Super_30_(film),Super 30,Super 30,0,2019,154,Biography|Drama,8.2,13972,Anand Kumar a Mathematics genius from a modes...,Based on life of Patna-based mathematician Ana...,Inspired by the Life of Anand Kumar & His Stud...,Hrithik Roshan|Mrunal Thakur|Nandish Singh|Vir...,NaN,12 July 2019 (USA)
143,Tumbbad,tt8239946,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Tumbbad,Tumbbad,Tumbbad,0,2018,104,Drama|Fantasy|Horror,8.2,16535,Set in Tumbbad in the 1920s the story revolve...,A mythological story about a goddess who creat...,NaN,Sohum Shah|Jyoti Malshe|Anita Date|Ronjini Cha...,9 wins & 12 nominations,12 October 2018 (India)
146,Andhadhun,tt8108198,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Andhadhun,Andhadhun,Andhadhun,0,2018,139,Crime|Thriller,8.4,51615,Akash a blind pianist is preparing for a Londo...,A series of mysterious events changes the life...,NaN,Ayushmann Khurrana|Tabu|Radhika Apte|Anil Dhaw...,24 wins & 25 nominations,5 October 2018 (USA)
325,Pink (2016 film),tt5571734,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Pink_(2016_film),Pink,Pink,0,2016,136,Drama|Thriller,8.2,33902,Deepak is a lawyer suffering from bipolar diso...,When three young women are implicated in a cri...,NaN,Taapsee Pannu|Amitabh Bachchan|Kirti Kulhari|A...,12 wins & 14 nominations,16 September 2016 (USA)
354,Dangal (film),tt5074352,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Dangal_(film),Dangal,Dangal,0,2016,161,Action|Biography|Drama,8.4,131338,Biopic of Mahavir Singh Phogat who taught wre...,Former wrestler Mahavir Singh Phogat and his t...,You think our girls are any lesser than boys?,Aamir Khan|Fatima Sana Shaikh|Sanya Malhotra|S...,23 wins & 4 nominations,21 December 2016 (USA)
418,Masaan,tt4635372,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Fly_Away_Solo,Masaan,Masaan,0,2015,109,Drama,8.1,19904,Four lives intersect along the Ganges: a low c...,Four lives intersect along the Ganges: a low c...,Paths of grieve intersect on the Ganges River.,Richa Chadha|Sanjay Mishra|Vicky Kaushal|Panka...,20 wins & 5 nominations,24 July 2015 (India)
426,Drishyam (2015 film),tt4430212,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Drishyam(2015),Drishyam,Drishyam,0,2015,163,Crime|Drama|Mystery,8.2,58340,Vijay Salgaonkar runs a cable TV network in a ...,Desperate measures are taken by a man who trie...,Remake of a Malayalam movie,Ajay Devgn|Shriya Saran|Tabu|Rajat Kapoor|Ishi...,1 win & 1 nomination,31 July 2015 (USA)
436,Talvar (film),tt4934950,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Talvar_(film),Talvar,Talvar,0,2015,132,Crime|Drama|Mystery,8.2,26612,The story revolves around the mysterious murde...,An experienced investigator confronts several ...,NaN,Irrfan Khan|Konkona Sen Sharma|Neeraj Kabi|Soh...,7 wins & 11 nominations,2 October 2015 (USA)
469,Queen (2014 film),tt3322420,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Queen_(2014_film),Queen,Queen,0,2013,146,Comedy|Drama,8.2,56406,Queen is a movie about growing up. Rani (Kanga...,A Delhi girl from a traditional family sets ou...,Everything in life happens for the good.,Kangana Ranaut|Rajkummar Rao|Lisa Haydon|Jeffr...,21 wins & 14 nominations,7 March 2014 (India)
536,Haider (film),tt3390572,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Haider_(film),Haider,Haider,0,2014,160,Action|Crime|Drama,8.1,46912,Vishal Bhardwaj's adaptation of William Shakes...,A young man returns to Kashmir after his fathe...,NaN,Tabu|Shahid Kapoor|Shraddha Kapoor|Kay Kay Men...,28 wins & 24 nominations,2 October 2014 (USA)
566,Ugly (film),tt2882328,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Ugly_(film),Ugly,Ugly,0,2013,128,Crime|Drama|Mystery,8.1,17483,The film portrays the kidnapping of a little g...,The case of a missing girl takes us through a ...,NaN,Rahul Bhat|Ronit Roy|Tejaswini Kolhapure|Viine...,3 wins & 12 nominations,26 December 2014 (India)
567,PK (film),tt2338151,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/PK_(film),PK,PK,0,2014,153,Comedy|Drama|Fantasy,8.1,143605,P. K. is a comedy of ideas about a stranger in...,An alien on Earth loses the only device he can...,NaN,Aamir Khan|Anushka Sharma|Saurabh Shukla|Sanja...,14 wins & 15 nominations,19 December 2014 (India)
589,Vishwaroopam,tt2199711,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Vishwaroop_(Hind...,Vishwaroopam,Vishwaroopam,0,2013,148,Action|Thriller,8.2,38016,Vishwanathan a Kathak dance teacher in New Yo...,When a classical dancer's suspecting wife sets...,NaN,Kamal Haasan|Rahul Bose|Shekhar Kapur|Pooja Ku...,5 wins & 11 nominations,25 January 2013 (India)
612,Bhaag Milkha Bhaag,tt2356180,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Bhaag_Milkha_Bhaag,Bhaag Milkha Bhaag,Bhaag Milkha Bhaag,0,2013,186,Biography|Drama|Sport,8.2,56205,"The true story of the ""Flying Sikh"" - world ch...",The truth behind the ascension of Milkha Singh...,The story unfolds July 12| 2013.,Farhan Akhtar|Sonam Kapoor|Pavan Malhotra|Art ...,52 wins & 34 nominations,12 July 2013 (USA)
638,Shahid (film),tt2181831,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Shahid_(film),Shahid,Shahid,0,2012,129,Biography|Crime|Drama,8.3,13537,Shahid traces the true story of slain human ri...,The account of Human Rights lawyer Shahid Azmi...,Based On The Life Of One Of The Most Controver...,Rajkummar Rao|Mohammed Zeeshan Ayyub|Baljinder...,10 wins & 6 nominations,18 October 2013 (India)
668,Paan Singh Tomar (film),tt1620933,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Paan_Singh_Tomar...,Paan Singh Tomar,Paan Singh Tomar,0,2012,135,Action|Biography|Crime,8.2,29994,Paan Singh Tomar is a Hindi-language film bas...,The story of Paan Singh Tomar an Indian athle...,NaN,Irrfan Khan|,10 wins & 11 nominations,2 March 2012 (USA)
669,Kahaani,tt1821480,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Kahaani,Kahaani,Kahaani,0,2012,122,Mystery|Thriller,8.1,53181,Kolkata is abuzz with the preparations for the...,A pregnant woman's search for her missing husb...,A mother of a story,Vidya Balan|Parambrata Chattopadhyay|Indraneil...,19 wins & 18 nominations,9 March 2012 (India)
693,Gangs of Wasseypur,tt1954470,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gangs_of_Wasseypur,Gangs of Wasseypur,Gangs of Wasseypur,0,2012,321,Action|Comedy|Crime,8.2,71636,Shahid Khan is exiled after impersonating the ...,A clash between Sultan and Shahid Khan leads t...,NaN,Manoj Bajpayee|Richa Chadha|Nawazuddin Siddiqu...,12 wins & 43 nominations,2 August 2012 (Singapore)
694,Gangs of Wasseypur – Part 2,tt1954470,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gangs_of_Wasseyp...,Gangs of Wasseypur,Gangs of Wasseypur,0,2012,321,Action|Comedy|Crime,8.2,71636,Shahid Khan is exiled after impersonating the ...,A clash between Sultan and Shahid Khan leads t...,NaN,Manoj Bajpayee|Richa Chadha|Nawazuddin Siddiqu...,12 wins & 43 nominations,2 August 2012 (Singapore)
709,Barfi!,tt2082197,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Barfi!,Barfi!,Barfi!,0,2012,151,Comedy|Drama|Romance,8.1,70443,Set in the 1970s in a pretty corner of India ...,Three young people learn that love can neither...,NaN,Ranbir Kapoor|Priyanka Chopra|Ileana D'Cruz|Sa...,50 wins & 28 nominations,14 September 2012 (India)
714,OMG – Oh My God!,tt2283748,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Oh_My_God_(2012_...,OMG: Oh My God!,OMG: Oh My God!,0,2012,125,Comedy|Drama|Fantasy,8.2,46072,Kanji Lalji Mehta though an atheist owns a s...,A shopkeeper takes God to court when his shop ...,Kanjibhai is taking God to court!,Paresh Rawal|Akshay Kumar|Mithun Chakraborty|O...,5 wins & 11 nominations,28 September 2012 (India)
778,Zindagi Na Milegi Dobara,tt1562872,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Zindagi_Na_Mileg...,Zindagi Na Milegi Dobara,Zindagi Na Milegi Dobara,0,2011,155,Comedy|Drama,8.1,60826,Three friends decide to turn their fantasy vac...,Three friends decide to turn their fantasy vac...,NaN,Hrithik Roshan|Farhan Akhtar|Abhay Deol|Katrin...,30 wins & 22 nominations,15 July 2011 (India)
869,Udaan (2010 film),tt1639426,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Udaan_(2010_film),Udaan,Udaan,0,2010,134,Drama,8.2,39567,After being abandoned for eight straight years...,Expelled from his school a 16-year old boy re...,NaN,Rajat Barmecha|Ronit Roy|Manjot Singh|Ram Kapo...,13 wins & 13 nominations,16 July 2010 (India)
912,3 Idiots,tt1187043,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/3_Idiots,3 Idiots,3 Idiots,0,2009,170,Comedy|Drama,8.4,310481,Farhan Qureshi and Raju Rastogi want to re-uni...,Two friends are searching for their long lost ...,Don't be Stupid. Be an I.D.I.O.T.,Aamir Khan|Madhavan|Sharman Joshi|Kareena Kapo...,57 wins & 18 nominations,25 December 2009 (India)
930,Gulaal (film),tt1261047,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gulaal_(film),Gulaal,Gulaal,0,2009,140,Crime|Drama|Thriller,8.1,12799,Bikaner-based 28-year-old Dilip Kumar Singh is...,A law student witnesses deception homicide a...,Love... Power... Revolution.,Kay Kay Menon|Raj Singh Chaudhary|Jesse Randha...,2 nominations,13 March 2009 (India)
1058,Black Friday (2007 film),tt0400234,https://upload.wikimedia.org/wikipedia/en/5/58...,https://en.wikipedia.org/wiki/Black_Friday_(20...,Black Friday,Black Friday,0,2004,143,Action|Crime|Drama,8.5,16761,A dramatic presentation of the bomb blasts tha...,Black Friday is a film about the investigation...,The story of the Bombay bomb blasts,Kay Kay Menon|Pavan Malhotra|Aditya Srivastava...,3 nominations,9 February 2007 (India)
1066,Chak De! India,tt0871510,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Chak_De!_India,Chak de! India,Chak De! India,0,2007,153,Drama|Family|Sport,8.2,68421,Kabir Khan (Shahrukh Khan) knows what it's lik...,Kabir Khan is the coach of the Indian Women's ...,Sometimes Winning is Everything,Shah Rukh Khan|Vidya Malvade|Sagarika Ghatge|S...,28 wins & 13 nominations,10 August 2007 (India)
1127,Taare Zameen Par,tt0986264,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Taare_Zameen_Par,Like Stars on Earth,Taare Zameen Par,0,2007,165,Drama|Family,8.4,148498,Ishaan Awasthi is an eight-year-old child whos...,An eight-year-old boy is thought to be a lazy ...,Every Child is Special,Darsheel Safary|Aamir Khan|Tisca Chopra|Vipin ...,18 wins & 8 nominations,21 December 2007 (India)
1180,Khosla Ka Ghosla,tt0466460,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Khosla_Ka_Ghosla,Khosla Ka Ghosla!,Khosla Ka Ghosla!,0,2006,135,Comedy|Crime|Drama,8.3,20538,K.K. Khosla (Anupam Kher) is a middle class ma...,A Delhi based retired middle class man tries h...,NaN,Anupam Kher|Boman Irani|Parvin Dabas|Tara Shar...,2 nominations,22 September 2006 (India)
1183,Lage Raho Munna Bhai,tt0456144,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Lage_Raho_Munna_...,Carry On Munna Bhai,Lage Raho Munna Bhai,0,2006,144,Comedy|Drama|Romance,8.1,39486,A hilarious underworld gangster known as Munna...,Munna Bhai embarks on a journey with Mahatma G...,Munnabhai meets Mahatma Gandhi,Sanjay Dutt|Arshad Warsi|Vidya Balan|Boman Ira...,19 wins & 16 nominations,1 September 2006 (USA)
1188,Omkara (2006 film),tt0488414,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Omkara_(2006_film),Omkara,Omkara,0,2006,155,Action|Crime|Drama,8.1,17594,Advocate Raghunath Mishra has arranged the mar...,A politically-minded enforcer's misguided trus...,NaN,Ajay Devgn|Saif Ali Khan|Vivek Oberoi|Kareena ...,19 wins & 20 nominations,28 July 2006 (USA)
1195,Rang De Basanti,tt0405508,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Rang_De_Basanti,Rang De Basanti,Rang De Basanti,0,2006,167,Comedy|Drama,8.2,103071,Sue comes to India to make a film on Indian re...,The story of six young Indians who assist an E...,A Generation Awakens.,Aamir Khan|Siddharth|Sharman Joshi|Kunal Kapoo...,Nominated for 1 BAFTA Film Award,26 January 2006 (USA)
1223,Black (2005 film),tt0375611,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Black_(2005_film),Black,Black,0,2005,122,Drama,8.2,31658,Based in Simla the McNallys are an Anglo-Indi...,The cathartic tale of a young woman who can't ...,An unending darkness... A world of shadows... ...,Amitabh Bachchan|Rani Mukerji|Shernaz Patel|Ay...,44 wins & 4 nominations,4 February 2005 (USA)
1252,Iqbal (film),tt0453729,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Iqbal_(film),Iqbal,Iqbal,0,2005,132,Drama|Sport,8.1,14864,India - a Nation obsessed with cricket - and i...,Iqbal the deaf and mute son of a farmer has ...,NaN,Shreyas Talpade|Naseeruddin Shah|Shweta Basu P...,9 wins & 13 nominations,20 January 2006 (USA)
1384,Swades,tt0367110,https://upload.wikimedia.org/wikipedia/en/8/85...,https://en.wikipedia.org/wiki/Swades,Swades,Swades: We the People,0,2004,210,Drama,8.2,76737,Set in modern day India Swades is a film that...,A successful Indian scientist returns to an In...,We| the people,Shah Rukh Khan|Gayatri Joshi|Kishori Ballal|Sm...,14 wins & 23 nominations,17 December 2004 (India)
1403,Munna Bhai M.B.B.S.,tt0374887,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Munna_Bhai_M.B.B.S.,Munna Bhai M.B.B.S.,Munna Bhai M.B.B.S.,0,2003,156,Comedy|Drama|Musical,8.1,67148,In India gangsters are called Bhai (brothers)....,A gangster sets out to fulfill his father's dr...,He might just cure you.,Sanjay Dutt|Arshad Warsi|Gracy Singh|Sunil Dut...,19 wins & 29 nominations,19 December 2003 (India)
1554,The Legend of Bhagat Singh,tt0319736,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Legend_of_Bh...,The Legend of Bhagat Singh,The Legend of Bhagat Singh,0,2002,155,Action|Biography|Drama,8.1,13455,Bhagat was born in British India during the ye...,The story of a young revolutionary who raised ...,NaN,Ajay Devgn|Sushant Singh|D. Santosh|Akhilendra...,11 wins & 5 nominations,7 June 2002 (India)
1567,Lagaan,tt0169102,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Lagaan,Lagaan: Once Upon a Time in India,Lagaan: Once Upon a Time in India,0,2001,224,Adventure|Drama|Musical,8.1,95686,This is the story about the resilience shown b...,The people of a small village in Victorian Ind...,Once upon a time in India,Aamir Khan|Gracy Singh|Rachel Shelley|Paul Bla...,Nominated for 1 Oscar,15 June 2001 (USA)
1568,Lagaan,tt0169102,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Lagaan:_Once_Upo...,Lagaan: Once Upon a Time in India,Lagaan: Once Upon a Time in India,0,2001,224,Adventure|Drama|Musical,8.1,95686,This is the story about the resilience shown b...,The people of a small village in Victorian Ind...,Once upon a time in India,Aamir Khan|Gracy Singh|Rachel Shelley|Paul Bla...,Nominated for 1 Oscar,15 June 2001 (USA)
1571,Dil Chahta Hai,tt0292490,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Dil_Chahta_Hai,Dil Chahta Hai,Dil Chahta Hai,0,2001,183,Comedy|Drama|Romance,8.1,62313,Three young men Akash Sameer and Siddharth a...,Three inseparable childhood friends are just o...,Welcome to a summer of their lives you will ne...,Aamir Khan|Saif Ali Khan|Akshaye Khanna|Preity...,22 wins & 37 nominations,10 August 2001 (India)

In [175]:
#Filter action movies with 8.0 or above imdb rating:-

mask1=movies['genres'].str.split('|').apply(lambda x: 'Action' in x)
mask2=movies['imdb_rating']>= 8.0

result=movies[mask1 & mask2]
result

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
41,Family of Thakurganj,tt8897986,https://upload.wikimedia.org/wikipedia/en/9/99...,https://en.wikipedia.org/wiki/Family_of_Thakur...,Family of Thakurganj,Family of Thakurganj,0,2019,127,Action|Drama,9.4,895,The film is based on small town of North India...,The film is based on small town of North India...,NaN,Jimmy Sheirgill|Mahie Gill|Nandish Singh|Prana...,NaN,19 July 2019 (India)
84,Mukkabaaz,tt7180544,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Mukkabaaz,The Brawler,Mukkabaaz,0,2017,154,Action|Drama|Sport,8.1,5434,A boxer (Shravan) belonging to upper cast tra...,A boxer struggles to make his mark in the boxi...,NaN,Viineet Kumar|Jimmy Sheirgill|Zoya Hussain|Rav...,3 wins & 6 nominations,12 January 2018 (USA)
219,Raag Desh (film),tt6080746,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Raagdesh,Raag Desh,Raag Desh,0,2017,135,Action|Drama|History,8.3,341,A period film based on the historic 1945 India...,A period film based on the historic 1945 India...,NaN,Kunal Kapoor|Amit Sadh|Mohit Marwah|Kenneth De...,NaN,28 July 2017 (India)
280,Laal Rang,tt5600714,NaN,https://en.wikipedia.org/wiki/Laal_Rang,Laal Rang,Laal Rang,0,2016,147,Action|Crime|Drama,8.0,3741,The friendship of two men is tested when thing...,The friendship of two men is tested when thing...,Every job good or bad| must be done with honesty.,Randeep Hooda|Akshay Oberoi|Rajniesh Duggall|P...,NaN,22 April 2016 (India)
354,Dangal (film),tt5074352,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Dangal_(film),Dangal,Dangal,0,2016,161,Action|Biography|Drama,8.4,131338,Biopic of Mahavir Singh Phogat who taught wre...,Former wrestler Mahavir Singh Phogat and his t...,You think our girls are any lesser than boys?,Aamir Khan|Fatima Sana Shaikh|Sanya Malhotra|S...,23 wins & 4 nominations,21 December 2016 (USA)
362,Bajrangi Bhaijaan,tt3863552,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Bajrangi_Bhaijaan,Bajrangi Bhaijaan,Bajrangi Bhaijaan,0,2015,163,Action|Comedy|Drama,8.0,65877,A little mute girl from a Pakistani village ge...,An Indian man with a magnanimous heart takes a...,NaN,Salman Khan|Harshaali Malhotra|Nawazuddin Sidd...,25 wins & 13 nominations,17 July 2015 (USA)
365,Baby (2015 Hindi film),tt3848892,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Baby_(2015_Hindi...,Baby,Baby,0,2015,159,Action|Thriller,8.0,49426,The country is perpetually under threat from t...,An elite counter-intelligence unit learns of a...,History Is Made By Those Who Give A Damn!,Akshay Kumar|Danny Denzongpa|Rana Daggubati|Ta...,1 win,23 January 2015 (India)
536,Haider (film),tt3390572,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Haider_(film),Haider,Haider,0,2014,160,Action|Crime|Drama,8.1,46912,Vishal Bhardwaj's adaptation of William Shakes...,A young man returns to Kashmir after his fathe...,NaN,Tabu|Shahid Kapoor|Shraddha Kapoor|Kay Kay Men...,28 wins & 24 nominations,2 October 2014 (USA)
589,Vishwaroopam,tt2199711,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Vishwaroop_(Hind...,Vishwaroopam,Vishwaroopam,0,2013,148,Action|Thriller,8.2,38016,Vishwanathan a Kathak dance teacher in New Yo...,When a classical dancer's suspecting wife sets...,NaN,Kamal Haasan|Rahul Bose|Shekhar Kapur|Pooja Ku...,5 wins & 11 nominations,25 January 2013 (India)
668,Paan Singh Tomar (film),tt1620933,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Paan_Singh_Tomar...,Paan Singh Tomar,Paan Singh Tomar,0,2012,135,Action|Biography|Crime,8.2,29994,Paan Singh Tomar is a Hindi-language film bas...,The story of Paan Singh Tomar an Indian athle...,NaN,Irrfan Khan|,10 wins & 11 nominations,2 March 2012 (USA)
693,Gangs of Wasseypur,tt1954470,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gangs_of_Wasseypur,Gangs of Wasseypur,Gangs of Wasseypur,0,2012,321,Action|Comedy|Crime,8.2,71636,Shahid Khan is exiled after impersonating the ...,A clash between Sultan and Shahid Khan leads t...,NaN,Manoj Bajpayee|Richa Chadha|Nawazuddin Siddiqu...,12 wins & 43 nominations,2 August 2012 (Singapore)
694,Gangs of Wasseypur – Part 2,tt1954470,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gangs_of_Wasseyp...,Gangs of Wasseypur,Gangs of Wasseypur,0,2012,321,Action|Comedy|Crime,8.2,71636,Shahid Khan is exiled after impersonating the ...,A clash between Sultan and Shahid Khan leads t...,NaN,Manoj Bajpayee|Richa Chadha|Nawazuddin Siddiqu...,12 wins & 43 nominations,2 August 2012 (Singapore)
1058,Black Friday (2007 film),tt0400234,https://upload.wikimedia.org/wikipedia/en/5/58...,https://en.wikipedia.org/wiki/Black_Friday_(20...,Black Friday,Black Friday,0,2004,143,Action|Crime|Drama,8.5,16761,A dramatic presentation of the bomb blasts tha...,Black Friday is a film about the investigation...,The story of the Bombay bomb blasts,Kay Kay Menon|Pavan Malhotra|Aditya Srivastava...,3 nominations,9 February 2007 (India)
1188,Omkara (2006 film),tt0488414,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Omkara_(2006_film),Omkara,Omkara,0,2006,155,Action|Crime|Drama,8.1,17594,Advocate Raghunath Mishra has arranged the mar...,A politically-minded enforcer's misguided trus...,NaN,Ajay Devgn|Saif Ali Khan|Vivek Oberoi|Kareena ...,19 wins & 20 nominations,28 July 2006 (USA)
1495,Company (film),tt0296574,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Company_(film),Company,Company,0,2002,155,Action|Crime|Drama,8.0,13474,Mallik is a henchman of Aslam Bhai a Mumbai u...,A small-time gangster named Chandu teams up wi...,A law & order enterprise,Ajay Devgn|Mohanlal|Manisha Koirala|Seema Bisw...,16 wins & 9 nominations,15 April 2002 (India)
1554,The Legend of Bhagat Singh,tt0319736,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Legend_of_Bh...,The Legend of Bhagat Singh,The Legend of Bhagat Singh,0,2002,155,Action|Biography|Drama,8.1,13455,Bhagat was born in British India during the ye...,The story of a young revolutionary who raised ...,NaN,Ajay Devgn|Sushant Singh|D. Santosh|Akhilendra...,11 wins & 5 nominations,7 June 2002 (India)

# Using isin() , .str.contains() & isna():-

In [177]:
#.Str.contains()- Using function-

#Filter action movies with 8.0 or above imdb rating:-

mask1=movies['genres'].str.contains('Action')
mask2=movies['imdb_rating']>= 8.0

result=movies[mask1 & mask2]
result

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
41,Family of Thakurganj,tt8897986,https://upload.wikimedia.org/wikipedia/en/9/99...,https://en.wikipedia.org/wiki/Family_of_Thakur...,Family of Thakurganj,Family of Thakurganj,0,2019,127,Action|Drama,9.4,895,The film is based on small town of North India...,The film is based on small town of North India...,NaN,Jimmy Sheirgill|Mahie Gill|Nandish Singh|Prana...,NaN,19 July 2019 (India)
84,Mukkabaaz,tt7180544,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Mukkabaaz,The Brawler,Mukkabaaz,0,2017,154,Action|Drama|Sport,8.1,5434,A boxer (Shravan) belonging to upper cast tra...,A boxer struggles to make his mark in the boxi...,NaN,Viineet Kumar|Jimmy Sheirgill|Zoya Hussain|Rav...,3 wins & 6 nominations,12 January 2018 (USA)
219,Raag Desh (film),tt6080746,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Raagdesh,Raag Desh,Raag Desh,0,2017,135,Action|Drama|History,8.3,341,A period film based on the historic 1945 India...,A period film based on the historic 1945 India...,NaN,Kunal Kapoor|Amit Sadh|Mohit Marwah|Kenneth De...,NaN,28 July 2017 (India)
280,Laal Rang,tt5600714,NaN,https://en.wikipedia.org/wiki/Laal_Rang,Laal Rang,Laal Rang,0,2016,147,Action|Crime|Drama,8.0,3741,The friendship of two men is tested when thing...,The friendship of two men is tested when thing...,Every job good or bad| must be done with honesty.,Randeep Hooda|Akshay Oberoi|Rajniesh Duggall|P...,NaN,22 April 2016 (India)
354,Dangal (film),tt5074352,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Dangal_(film),Dangal,Dangal,0,2016,161,Action|Biography|Drama,8.4,131338,Biopic of Mahavir Singh Phogat who taught wre...,Former wrestler Mahavir Singh Phogat and his t...,You think our girls are any lesser than boys?,Aamir Khan|Fatima Sana Shaikh|Sanya Malhotra|S...,23 wins & 4 nominations,21 December 2016 (USA)
362,Bajrangi Bhaijaan,tt3863552,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Bajrangi_Bhaijaan,Bajrangi Bhaijaan,Bajrangi Bhaijaan,0,2015,163,Action|Comedy|Drama,8.0,65877,A little mute girl from a Pakistani village ge...,An Indian man with a magnanimous heart takes a...,NaN,Salman Khan|Harshaali Malhotra|Nawazuddin Sidd...,25 wins & 13 nominations,17 July 2015 (USA)
365,Baby (2015 Hindi film),tt3848892,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Baby_(2015_Hindi...,Baby,Baby,0,2015,159,Action|Thriller,8.0,49426,The country is perpetually under threat from t...,An elite counter-intelligence unit learns of a...,History Is Made By Those Who Give A Damn!,Akshay Kumar|Danny Denzongpa|Rana Daggubati|Ta...,1 win,23 January 2015 (India)
536,Haider (film),tt3390572,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Haider_(film),Haider,Haider,0,2014,160,Action|Crime|Drama,8.1,46912,Vishal Bhardwaj's adaptation of William Shakes...,A young man returns to Kashmir after his fathe...,NaN,Tabu|Shahid Kapoor|Shraddha Kapoor|Kay Kay Men...,28 wins & 24 nominations,2 October 2014 (USA)
589,Vishwaroopam,tt2199711,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Vishwaroop_(Hind...,Vishwaroopam,Vishwaroopam,0,2013,148,Action|Thriller,8.2,38016,Vishwanathan a Kathak dance teacher in New Yo...,When a classical dancer's suspecting wife sets...,NaN,Kamal Haasan|Rahul Bose|Shekhar Kapur|Pooja Ku...,5 wins & 11 nominations,25 January 2013 (India)
668,Paan Singh Tomar (film),tt1620933,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Paan_Singh_Tomar...,Paan Singh Tomar,Paan Singh Tomar,0,2012,135,Action|Biography|Crime,8.2,29994,Paan Singh Tomar is a Hindi-language film bas...,The story of Paan Singh Tomar an Indian athle...,NaN,Irrfan Khan|,10 wins & 11 nominations,2 March 2012 (USA)
693,Gangs of Wasseypur,tt1954470,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gangs_of_Wasseypur,Gangs of Wasseypur,Gangs of Wasseypur,0,2012,321,Action|Comedy|Crime,8.2,71636,Shahid Khan is exiled after impersonating the ...,A clash between Sultan and Shahid Khan leads t...,NaN,Manoj Bajpayee|Richa Chadha|Nawazuddin Siddiqu...,12 wins & 43 nominations,2 August 2012 (Singapore)
694,Gangs of Wasseypur – Part 2,tt1954470,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gangs_of_Wasseyp...,Gangs of Wasseypur,Gangs of Wasseypur,0,2012,321,Action|Comedy|Crime,8.2,71636,Shahid Khan is exiled after impersonating the ...,A clash between Sultan and Shahid Khan leads t...,NaN,Manoj Bajpayee|Richa Chadha|Nawazuddin Siddiqu...,12 wins & 43 nominations,2 August 2012 (Singapore)
1058,Black Friday (2007 film),tt0400234,https://upload.wikimedia.org/wikipedia/en/5/58...,https://en.wikipedia.org/wiki/Black_Friday_(20...,Black Friday,Black Friday,0,2004,143,Action|Crime|Drama,8.5,16761,A dramatic presentation of the bomb blasts tha...,Black Friday is a film about the investigation...,The story of the Bombay bomb blasts,Kay Kay Menon|Pavan Malhotra|Aditya Srivastava...,3 nominations,9 February 2007 (India)
1188,Omkara (2006 film),tt0488414,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Omkara_(2006_film),Omkara,Omkara,0,2006,155,Action|Crime|Drama,8.1,17594,Advocate Raghunath Mishra has arranged the mar...,A politically-minded enforcer's misguided trus...,NaN,Ajay Devgn|Saif Ali Khan|Vivek Oberoi|Kareena ...,19 wins & 20 nominations,28 July 2006 (USA)
1495,Company (film),tt0296574,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Company_(film),Company,Company,0,2002,155,Action|Crime|Drama,8.0,13474,Mallik is a henchman of Aslam Bhai a Mumbai u...,A small-time gangster named Chandu teams up wi...,A law & order enterprise,Ajay Devgn|Mohanlal|Manisha Koirala|Seema Bisw...,16 wins & 9 nominations,15 April 2002 (India)
1554,The Legend of Bhagat Singh,tt0319736,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Legend_of_Bh...,The Legend of Bhagat Singh,The Legend of Bhagat Singh,0,2002,155,Action|Biography|Drama,8.1,13455,Bhagat was born in British India during the ye...,The story of a young revolutionary who raised ...,NaN,Ajay Devgn|Sushant Singh|D. Santosh|Akhilendra...,11 wins & 5 nominations,7 June 2002 (India)

In [210]:
# another example of .str.contains()-

#Filter movies akshay kumar & salman khan together-

mask1=movies['actors'].str.contains('Akshay kumar',case=False, na=False)  
mask1=movies['actors'].str.contains('salman khan',case=False, na=False)

#case = False--> it handles the lower,upper and all size capital letters
#na = False--> it false the NaN values

result= movies[mask1 & mask2]
result

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
1176,Jaan-E-Mann,tt0456481,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Jaan-E-Mann,Jaan-E-Mann: Let's Fall in Love... Again,Jaan-E-Mann: Let's Fall in Love... Again,0,2006,165,Drama|Musical|Romance,6.0,7571,Suhaan receives divorce notice from his wife P...,Follows a love triangle between Agastya Suhaa...,Are you ready to fall in love..... again?,Salman Khan|Akshay Kumar|Preity Zinta|Anupam K...,1 nomination,20 October 2006 (India)
1316,Mujhse Shaadi Karogi,tt0418362,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Mujhse_Shaadi_Ka...,Mujhse Shaadi Karogi,Mujhse Shaadi Karogi,0,2004,163,Comedy|Drama|Musical,6.7,12411,Sunny rents a room in a City called Goa in Ind...,Sameer fast at losing his temper is re-locate...,How to win a girl's heart,Salman Khan|Akshay Kumar|Priyanka Chopra|Amris...,6 wins & 28 nominations,30 July 2004 (USA)

In [215]:
# Using isin()-

ipl[ipl['Team1'].isin(['Mumbai Indians', 'Chennai Super Kings'])]

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
6,1304114,Mumbai,2022-05-20,2022,68,Chennai Super Kings,Rajasthan Royals,"Brabourne Stadium, Mumbai",Chennai Super Kings,bat,N,Rajasthan Royals,Wickets,5.0,NaN,R Ashwin,"['RD Gaikwad', 'DP Conway', 'MM Ali', 'N Jagad...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,NA Patwardhan
12,1304108,Mumbai,2022-05-15,2022,62,Chennai Super Kings,Gujarat Titans,"Wankhede Stadium, Mumbai",Chennai Super Kings,bat,N,Gujarat Titans,Wickets,7.0,NaN,WP Saha,"['RD Gaikwad', 'DP Conway', 'MM Ali', 'N Jagad...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",R Pandit,VK Sharma
15,1304105,Mumbai,2022-05-12,2022,59,Chennai Super Kings,Mumbai Indians,"Wankhede Stadium, Mumbai",Mumbai Indians,field,N,Mumbai Indians,Wickets,5.0,NaN,DR Sams,"['RD Gaikwad', 'DP Conway', 'MM Ali', 'RV Utha...","['Ishan Kishan', 'RG Sharma', 'DR Sams', 'Tila...",Chirra Ravikanthreddy,CB Gaffaney
19,1304101,Navi Mumbai,2022-05-08,2022,55,Chennai Super Kings,Delhi Capitals,"Dr DY Patil Sports Academy, Mumbai",Delhi Capitals,field,N,Chennai Super Kings,Runs,91.0,NaN,DP Conway,"['RD Gaikwad', 'DP Conway', 'S Dube', 'AT Rayu...","['DA Warner', 'KS Bharat', 'MR Marsh', 'RR Pan...",Nitin Menon,R Pandit
23,1304097,Mumbai,2022-05-06,2022,51,Mumbai Indians,Gujarat Titans,"Brabourne Stadium, Mumbai",Gujarat Titans,field,N,Mumbai Indians,Runs,5.0,NaN,TH David,"['Ishan Kishan', 'RG Sharma', 'SA Yadav', 'Til...","['WP Saha', 'Shubman Gill', 'HH Pandya', 'B Sa...",J Madanagopal,GR Sadashiv Iyer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
930,336001,Chennai,2008-05-02,2007/08,20,Chennai Super Kings,Delhi Daredevils,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,bat,N,Delhi Daredevils,Wickets,8.0,NaN,V Sehwag,"['PA Patel', 'SP Fleming', 'S Vidyut', 'MS Dho...","['G Gambhir', 'V Sehwag', 'AB de Villiers', 'S...",BF Bowden,K Hariharan
937,335994,Mumbai,2008-04-27,2007/08,14,Mumbai Indians,Deccan Chargers,Dr DY Patil Sports Academy,Deccan Chargers,field,N,Deccan Chargers,Wickets,10.0,NaN,AC Gilchrist,"['L Ronchi', 'ST Jayasuriya', 'AM Rahane', 'RV...","['AC Gilchrist', 'VVS Laxman', 'A Symonds', 'R...",Asad Rauf,SL Shastri
938,335993,Chennai,2008-04-26,2007/08,11,Chennai Super Kings,Kolkata Knight Riders,"MA Chidambaram Stadium, Chepauk",Kolkata Knight Riders,bat,N,Chennai Super Kings,Wickets,9.0,NaN,JDP Oram,"['PA Patel', 'ML Hayden', 'MS Dhoni', 'MEK Hus...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'W...",BF Bowden,AV Jayaprakash
942,335989,Chennai,2008-04-23,2007/08,8,Chennai Super Kings,Mumbai Indians,"MA Chidambaram Stadium, Chepauk",Mumbai Indians,field,N,Chennai Super Kings,Runs,6.0,NaN,ML Hayden,"['PA Patel', 'ML Hayden', 'MEK Hussey', 'SK Ra...","['L Ronchi', 'ST Jayasuriya', 'RV Uthappa', 'S...",DJ Harper,GA Pratapkumar
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper

In [220]:
# all matches of season 2018 and 2020-

ipl[ipl['Season'].isin(['2018', '2020'])]

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
254,1136620,Mumbai,2018-05-27,2018,Final,Sunrisers Hyderabad,Chennai Super Kings,Wankhede Stadium,Chennai Super Kings,field,N,Chennai Super Kings,Wickets,8.0,NaN,SR Watson,"['SP Goswami', 'S Dhawan', 'KS Williamson', 'S...","['SR Watson', 'F du Plessis', 'SK Raina', 'AT ...",M Erasmus,S Ravi
255,1136619,Kolkata,2018-05-25,2018,Qualifier,Sunrisers Hyderabad,Kolkata Knight Riders,Eden Gardens,Kolkata Knight Riders,field,N,Sunrisers Hyderabad,Runs,14.0,NaN,Rashid Khan,"['WP Saha', 'S Dhawan', 'KS Williamson', 'Shak...","['CA Lynn', 'SP Narine', 'N Rana', 'RV Uthappa...",HDPK Dharmasena,Nitin Menon
256,1136618,Kolkata,2018-05-23,2018,Eliminator,Kolkata Knight Riders,Rajasthan Royals,Eden Gardens,Rajasthan Royals,field,N,Kolkata Knight Riders,Runs,25.0,NaN,AD Russell,"['SP Narine', 'CA Lynn', 'RV Uthappa', 'N Rana...","['AM Rahane', 'RA Tripathi', 'SV Samson', 'H K...",AK Chaudhary,Nitin Menon
257,1136617,Mumbai,2018-05-22,2018,Qualifier,Sunrisers Hyderabad,Chennai Super Kings,Wankhede Stadium,Chennai Super Kings,field,N,Chennai Super Kings,Wickets,2.0,NaN,F du Plessis,"['S Dhawan', 'SP Goswami', 'KS Williamson', 'M...","['SR Watson', 'F du Plessis', 'SK Raina', 'AT ...",C Shamshuddin,M Erasmus
258,1136616,Pune,2018-05-20,2018,56,Kings XI Punjab,Chennai Super Kings,Maharashtra Cricket Association Stadium,Chennai Super Kings,field,N,Chennai Super Kings,Wickets,5.0,NaN,L Ngidi,"['KL Rahul', 'CH Gayle', 'AJ Finch', 'MK Tiwar...","['AT Rayudu', 'F du Plessis', 'SK Raina', 'SW ...",Nitin Menon,YC Barde
259,1136615,Delhi,2018-05-20,2018,55,Delhi Daredevils,Mumbai Indians,Arun Jaitley Stadium,Delhi Daredevils,bat,N,Delhi Daredevils,Runs,11.0,NaN,A Mishra,"['PP Shaw', 'GJ Maxwell', 'SS Iyer', 'RR Pant'...","['SA Yadav', 'E Lewis', 'Ishan Kishan', 'KA Po...",HDPK Dharmasena,CK Nandan
260,1136614,Hyderabad,2018-05-19,2018,54,Sunrisers Hyderabad,Kolkata Knight Riders,Rajiv Gandhi International Stadium,Sunrisers Hyderabad,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,CA Lynn,"['S Dhawan', 'SP Goswami', 'KS Williamson', 'M...","['CA Lynn', 'SP Narine', 'RV Uthappa', 'KD Kar...",AK Chaudhary,S Ravi
261,1136613,Jaipur,2018-05-19,2018,53,Rajasthan Royals,Royal Challengers Bangalore,Sawai Mansingh Stadium,Rajasthan Royals,bat,N,Rajasthan Royals,Runs,30.0,NaN,S Gopal,"['RA Tripathi', 'JC Archer', 'AM Rahane', 'SV ...","['V Kohli', 'PA Patel', 'AB de Villiers', 'MM ...",BNJ Oxenford,VK Sharma
262,1136612,Delhi,2018-05-18,2018,52,Delhi Daredevils,Chennai Super Kings,Arun Jaitley Stadium,Chennai Super Kings,field,N,Delhi Daredevils,Runs,34.0,NaN,HV Patel,"['PP Shaw', 'SS Iyer', 'RR Pant', 'GJ Maxwell'...","['SR Watson', 'AT Rayudu', 'SK Raina', 'MS Dho...",HDPK Dharmasena,VA Kulkarni
263,1136611,Bengaluru,2018-05-17,2018,51,Royal Challengers Bangalore,Sunrisers Hyderabad,M.Chinnaswamy Stadium,Sunrisers Hyderabad,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,AB de Villiers,"['PA Patel', 'V Kohli', 'AB de Villiers', 'MM ...","['S Dhawan', 'AD Hales', 'KS Williamson', 'MK ...",AY Dandekar,S Ravi
264,1136610,Mumbai,2018-05-16,2018,50,Mumbai Indians,Kings XI Punjab,Wankhede Stadium,Kings XI Punjab,field,N,Mumbai Indians,Runs,3.0,NaN,JJ Bumrah,"['SA Yadav', 'E Lewis', 'Ishan Kishan', 'RG Sh...","['KL Rahul', 'CH Gayle', 'AJ Finch', 'MP Stoin...",M Erasmus,Nitin Menon
265,1136609,Kolkata,2018-05-15,2018,49,Rajasthan Royals,Kolkata Knight Riders,Eden Gardens,Kolkata Knight Riders,field,N,Kolkata Knight Riders,Wickets,6.0,NaN,Kuldeep Yadav,"['RA Tripathi', 'JC Buttler', 'AM Rahane', 'SV...","['SP Narine', 'CA Lynn', 'RV Uthappa', 'N Rana...",AK Chaudhary,HDPK Dharmasena
266,1136608,Indore,2018-05-14,2018,48,Kings XI Punjab,Royal Challengers Bangalore,Holkar Cricket Stadium,Royal Challengers Bangalore,field,N,Royal Challengers Bangalore,Wickets,10.0,NaN,UT Yadav,"['KL Rahul', 'CH Gayle', 'KK Nair', 'AJ Finch'...","['V Kohli', 'PA Patel', 'MM Ali', 'AB de Villi...",BNJ Oxenford,VK Sharma
267,1136607,Mumbai,2018-05-13,2018,47,Mumbai Indians,Rajasthan Royals,Wankhede Stadium,Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['SA Yadav', 'E Lewis', 'RG Sharma', 'Ishan Ki...","['DJM Short', 'JC Buttler', 'AM Rahane', 'SV S...",Nitin Menon,S Ravi
268,1136606,Pune,2018-05-13,2018,46,Sunrisers Hyderabad,Chennai Super Kings,Maharashtra Cricket Association Stadium,Chennai Super Kings,field,N,Chennai Super Kings,Wickets,8.0,NaN,AT Rayudu,"['S Dhawan', 'AD Hales', 'KS Williamson', 'MK ...","['SR Watson', 'AT Rayudu', 'SK Raina', 'MS Dho...",M Erasmus,YC Barde
269,1136605,Delhi,2018-05-12,2018,45,Delhi Daredevils,Royal Challengers Bangalore,Arun Jaitley Stadium,Royal Challengers Bangalore,field,N,Royal Challengers Bangalore,Wickets,5.0,NaN,AB de Villiers,"['PP Shaw', 'JJ Roy', 'SS Iyer', 'RR Pant', 'V...","['PA Patel', 'MM Ali', 'V Kohli', 'AB de Villi...",KN Ananthapadmanabhan,HDPK Dharmasena
270,1136604,Indore,2018-05-12,2018,44,Kolkata Knight Riders,Kings XI Punjab,Holkar Cricket Stadium,Kings XI Punjab,field,N,Kolkata Knight Riders,Runs,31.0,NaN,SP Narine,"['CA Lynn', 'SP Narine', 'RV Uthappa', 'AD Rus...","['KL Rahul', 'CH Gayle', 'MA Agarwal', 'KK Nai...",CK Nandan,VK Sharma
271,1136603,Jaipur,2018-05-11,2018,43,Chennai Super Kings,Rajasthan Royals,Sawai Mansingh Stadium,Chennai Super Kings,bat,N,Rajasthan Royals,Wickets,4.0,NaN,JC Buttler,"['SR Watson', 'AT Rayudu', 'SK Raina', 'MS Dho...","['JC Buttler', 'BA Stokes', 'AM Rahane', 'SV S...",M Erasmus,YC Barde
272,1136602,Delhi,2018-05-10,2018,42,Delhi Daredevils,Sunrisers Hyderabad,Arun Jaitley Stadium,Delhi Daredevils,bat,N,Sunrisers Hyderabad,Wickets,9.0,NaN,S Dhawan,"['PP Shaw', 'JJ Roy', 'SS Iyer', 'RR Pant', 'H...","['AD Hales', 'S Dhawan', 'KS Williamson', 'MK ...",AY Dandekar,C Shamshuddin
273,1136601,Kolkata,2018-05-09,2018,41,Mumbai Indians,Kolkata Knight Riders,Eden Gardens,Kolkata Knight Riders,field,N,Mumbai Indians,Runs,102.0,NaN,Ishan Kishan,"['SA Yadav', 'E Lewis', 'RG Sharma', 'Ishan Ki...","['SP Narine', 'CA Lynn', 'RV Uthappa', 'N Rana...",KN Ananthapadmanabhan,AK Chaudhary
274,1136600,Jaipur,2018-05-08,2018,40,Rajasthan Royals,Kings XI Punjab,Sawai Mansingh Stadium,Rajasthan Royals,bat,N,Rajasthan Royals,Runs,15.0,NaN,JC Buttler,"['AM Rahane', 'JC Buttler', 'K Gowtham', 'SV S...","['KL Rahul', 'CH Gayle', 'R Ashwin', 'KK Nair'...",M Erasmus,Nitin Menon
275,1136599,Hyderabad,2018-05-07,2018,39,Sunrisers Hyderabad,Royal Challengers Bangalore,Rajiv Gandhi International Stadium,Royal Challengers Bangalore,field,N,Sunrisers Hyderabad,Runs,5.0,NaN,KS Williamson,"['AD Hales', 'S Dhawan', 'KS Williamson', 'MK ...","['M Vohra', 'PA Patel', 'V Kohli', 'AB de Vill...",BNJ Oxenford,VK Sharma
276,1136598,Indore,2018-05-06,2018,38,Rajasthan Royals,Kings XI Punjab,Holkar Cricket Stadium,Kings XI Punjab,field,N,Kings XI Punjab,Wickets,6.0,NaN,Mujeeb Ur Rahman,"['JC Buttler', 'DJM Short', 'AM Rahane', 'SV S...","['KL Rahul', 'CH Gayle', 'MA Agarwal', 'KK Nai...",C Shamshuddin,S Ravi
277,1136597,Mumbai,2018-05-06,2018,37,Mumbai Indians,Kolkata Knight Riders,Wankhede Stadium,Kolkata Knight Riders,field,N,Mumbai Indians,Runs,13.0,NaN,HH Pandya,"['SA Yadav', 'E Lewis', 'RG Sharma', 'HH Pandy...","['CA Lynn', 'Shubman Gill', 'RV Uthappa', 'N R...",A Deshmukh,HDPK Dharmasena
278,1136596,Hyderabad,2018-05-05,2018,36,Delhi Daredevils,Sunrisers Hyderabad,Rajiv Gandhi International Stadium,Delhi Daredevils,bat,N,Sunrisers Hyderabad,Wickets,7.0,NaN,Rashid Khan,"['PP Shaw', 'GJ Maxwell', 'SS Iyer', 'RR Pant'...","['AD Hales', 'S Dhawan', 'KS Williamson', 'MK ...",BNJ Oxenford,CK Nandan
279,1136595,Pune,2018-05-05,2018,35,Royal Challengers Bangalore,Chennai Super Kings,Maharashtra Cricket Association Stadium,Chennai Super Kings,field,N,Chennai Super Kings,Wickets,6.0,NaN,RA Jadeja,"['PA Patel', 'BB McCullum', 'V Kohli', 'AB de ...","['SR Watson', 'AT Rayudu', 'SK Raina', 'DR Sho...",Nitin Menon,YC Barde
280,1136594,Indore,2018-05-04,2018,34,Kings XI Punjab,Mumbai Indians,Holkar Cricket Stadium,Mumbai Indians,field,N,Mumbai Indians,Wickets,6.0,NaN,SA Yadav,"['KL Rahul', 'CH Gayle', 'Yuvraj Singh', 'KK N...","['SA Yadav', 'E Lewis', 'Ishan Kishan', 'HH Pa...",AY Dandekar,S Ravi
281,1136593,Kolkata,2018-05-03,2018,33,Chennai Super Kings,Kolkata Knight Riders,Eden Gardens,Kolkata Knight Riders,field,N,Kolkata Knight Riders,Wickets,6.0,NaN,SP Narine,"['SR Watson', 'F du Plessis', 'SK Raina', 'AT ...","['CA Lynn', 'SP Narine', 'RV Uthappa', 'Shubma...",A Deshmukh,HDPK Dharmasena
282,1136592,Delhi,2018-05-02,2018,32,Delhi Daredevils,Rajasthan Royals,Arun Jaitley Stadium,Rajasthan Royals,field,N,Delhi Daredevils,Runs,4.0,D/L,RR Pant,"['PP Shaw', 'C Munro', 'SS Iyer', 'RR Pant', '...","['DJM Short', 'JC Buttler', 'SV Samson', 'BA S...",CK Nandan,VK Sharma
283,1136591,Bengaluru,2018-05-01,2018,31,Royal Challengers Bangalore,Mumbai Indians,M.Chinnaswamy Stadium,Mumbai Indians,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,TG Southee,"['M Vohra', 'Q de Kock', 'BB McCullum', 'V Koh...","['SA Yadav', 'Ishan Kishan', 'JP Duminy', 'RG ...",M Erasmus,Nitin Menon
284,1136590,Pune,2018-04-30,2018,30,Chennai Super Kings,Delhi Daredevils,Maharashtra Cricket Association Stadium,Delhi Daredevils,field,N,Chennai Super Kings,Runs,13.0,NaN,SR Watson,"['SR Watson', 'F du Plessis', 'SK Raina', 'AT ...","['PP Shaw', 'C Munro', 'SS Iyer', 'RR Pant', '...",AY Dandekar,C Shamshuddin
285,1136588,Jaipur,2018-04-29,2018,28,Sunrisers Hyderabad,Rajasthan Royals,Sawai Mansingh Stadium,Sunrisers Hyderabad,bat,N,Sunrisers Hyderabad,Runs,11.0,NaN,KS Williamson,"['AD Hales', 'S Dhawan', 'KS Williamson', 'MK ...","['AM Rahane', 'RA Tripathi', 'SV Samson', 'BA ...",BNJ Oxenford,A Nand Kishore
286,1136589,Bengaluru,2018-04-29,2018,29,Royal Challengers Bangalore,Kolkata Knight Riders,M.Chinnaswamy Stadium,Kolkata Knight Riders,field,N,Kolkata Knight Riders,Wickets,6.0,NaN,CA Lynn,"['Q de Kock', 'BB McCullum', 'V Kohli', 'M Voh...","['CA Lynn', 'SP Narine', 'RV Uthappa', 'N Rana...",AK Chaudhary,NJ Llong
287,1136587,Pune,2018-04-28,2018,27,Chennai Super Kings,Mumbai Indians,Maharashtra Cricket Association Stadium,Mumbai Indians,field,N,Mumbai Indians,Wickets,8.0,NaN,RG Sharma,"['SR Watson', 'AT Rayudu', 'SK Raina', 'MS Dho...","['SA Yadav', 'E Lewis', 'RG Sharma', 'HH Pandy...",CB Gaffaney,Nitin Menon
288,1136586,Delhi,2018-04-27,2018,26,Delhi Daredevils,Kolkata Knight Riders,Arun Jaitley Stadium,Kolkata Knight Riders,field,N,Delhi Daredevils,Runs,55.0,NaN,SS Iyer,"['PP Shaw', 'C Munro', 'SS Iyer', 'RR Pant', '...","['CA Lynn', 'SP Narine', 'RV Uthappa', 'N Rana...",C Shamshuddin,S Ravi
289,1136585,Hyderabad,2018-04-26,2018,25,Sunrisers Hyderabad,Kings XI Punjab,Rajiv Gandhi International Stadium,Kings XI Punjab,field,N,Sunrisers Hyderabad,Runs,13.0,NaN,AS Rajpoot,"['S Dhawan', 'KS Williamson', 'WP Saha', 'MK P...","['KL Rahul', 'CH Gayle', 'MA Agarwal', 'KK Nai...",CK Nandan,YC Barde
290,1136584,Bengaluru,2018-04-25,2018,24,Royal Challengers Bangalore,Chennai Super Kings,M.Chinnaswamy Stadium,Chennai Super Kings,field,N,Chennai Super Kings,Wickets,5.0,NaN,MS Dhoni,"['Q de Kock', 'V Kohli', 'AB de Villiers', 'CJ...","['SR Watson', 'AT Rayudu', 'SK Raina', 'SW Bil...",NJ Llong,VK Sharma
291,1136583,Mumbai,2018-04-24,2018,23,Sunrisers Hyderabad,Mumbai Indians,Wankhede Stadium,Mumbai Indians,field,N,Sunrisers Hyderabad,Runs,31.0,NaN,Rashid Khan,"['S Dhawan', 'KS Williamson', 'WP Saha', 'MK P...","['SA Yadav', 'E Lewis', 'Ishan Kishan', 'RG Sh...",C Shamshuddin,S Ravi
292,1136582,Delhi,2018-04-23,2018,22,Kings XI Punjab,Delhi Daredevils,Arun Jaitley Stadium,Delhi Daredevils,field,N,Kings XI Punjab,Runs,4.0,NaN,AS Rajpoot,"['KL Rahul', 'AJ Finch', 'MA Agarwal', 'KK Nai...","['PP Shaw', 'G Gambhir', 'GJ Maxwell', 'SS Iye...",A Nand Kishore,CK Nandan
293,1136581,Jaipur,2018-04-22,2018,21,Mumbai Indians,Rajasthan Royals,Sawai Mansingh Stadium,Mumbai Indians,bat,N,Rajasthan Royals,Wickets,3.0,NaN,JC Archer,"['SA Yadav', 'E Lewis', 'Ishan Kishan', 'KA Po...","['AM Rahane', 'RA Tripathi', 'SV Samson', 'BA ...",KN Ananthapadmanabhan,RJ Tucker
294,1136580,Hyderabad,2018-04-22,2018,20,Chennai Super Kings,Sunrisers Hyderabad,Rajiv Gandhi International Stadium,Sunrisers Hyderabad,field,N,Chennai Super Kings,Runs,4.0,NaN,AT Rayudu,"['SR Watson', 'F du Plessis', 'SK Raina', 'AT ...","['RK Bhui', 'KS Williamson', 'MK Pandey', 'DJ ...",AK Chaudhary,VA Kulkarni
295,1136579,Bengaluru,2018-04-21,2018,19,Delhi Daredevils,Royal Challengers Bangalore,M.Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Royal Challengers Bangalore,Wickets,6.0,NaN,AB de Villiers,"['JJ Roy', 'G Gambhir', 'SS Iyer', 'RR Pant', ...","['Q de Kock', 'M Vohra', 'V Kohli', 'AB de Vil...",CB Gaffaney,CK Nandan
296,1136578,Kolkata,2018-04-21,2018,18,Kolkata Knight Riders,Kings XI Punjab,Eden Gardens,Kings XI Punjab,field,N,Kings XI Punjab,Wickets,9.0,D/L,KL Rahul,"['CA Lynn', 'SP Narine', 'RV Uthappa', 'N Rana...","['KL Rahul', 'CH Gayle', 'MA Agarwal', 'KK Nai...",A Deshmukh,C Shamshuddin
297,1136577,Pune,2018-04-20,2018,17,Chennai Super Kings,Rajasthan Royals,Maharashtra Cricket Association Stadium,Rajasthan Royals,field,N,Chennai Super Kings,Runs,64.0,NaN,SR Watson,"['SR Watson', 'AT Rayudu', 'SK Raina', 'MS Dho...","['AM Rahane', 'H Klaasen', 'SV Samson', 'BA St...",KN Ananthapadmanabhan,Nitin Menon
298,1136576,Chandigarh,2018-04-19,2018,16,Kings XI Punjab,Sunrisers Hyderabad,Punjab Cricket Association IS Bindra Stadium,Kings XI Punjab,bat,N,Kings XI Punjab,Runs,15.0,NaN,CH Gayle,"['KL Rahul', 'CH Gayle', 'MA Agarwal', 'KK Nai...","['WP Saha', 'S Dhawan', 'KS Williamson', 'YK P...",AK Chaudhary,NJ Llong
299,1136575,Jaipur,2018-04-18,2018,15,Rajasthan Royals,Kolkata Knight Riders,Sawai Mansingh Stadium,Kolkata Knight Riders,field,N,Kolkata Knight Riders,Wickets,7.0,NaN,N Rana,"['AM Rahane', 'DJM Short', 'SV Samson', 'RA Tr...","['SP Narine', 'CA Lynn', 'RV Uthappa', 'N Rana...",A Deshmukh,S Ravi
300,1136574,Mumbai,2018-04-17,2018,14,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Royal Challengers Bangalore,field,N,Mumbai Indians,Runs,46.0,NaN,RG Sharma,"['SA Yadav', 'E Lewis', 'Ishan Kishan', 'RG Sh...","['V Kohli', 'Q de Kock', 'AB de Villiers', 'Ma...",Nitin Menon,RJ Tucker
301,1136573,Kolkata,2018-04-16,2018,13,Kolkata Knight Riders,Delhi Daredevils,Eden Gardens,Delhi Daredevils,field,N,Kolkata Knight Riders,Runs,71.0,NaN,N Rana,"['CA Lynn', 'SP Narine', 'RV Uthappa', 'N Rana...","['G Gambhir', 'JJ Roy', 'SS Iyer', 'RR Pant', ...",AK Chaudhary,A Nand Kishore
302,1136572,Chandigarh,2018-04-15,2018,12,Kings XI Punjab,Chennai Super Kings,Punjab Cricket Association IS Bindra Stadium,Chennai Super Kings,field,N,Kings XI Punjab,Runs,4.0,NaN,CH Gayle,"['KL Rahul', 'CH Gayle', 'MA Agarwal', 'Yuvraj...","['SR Watson', 'M Vijay', 'AT Rayudu', 'SW Bill...",CK Nandan,VA Kulkarni
303,1136571,Bengaluru,2018-04-15,2018,11,Rajasthan Royals,Royal Challengers Bangalore,M.Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Rajasthan Royals,Runs,19.0,NaN,SV Samson,"['AM Rahane', 'DJM Short', 'SV Samson', 'BA St...","['BB McCullum', 'Q de Kock', 'V Kohli', 'AB de...",C Shamshuddin,S Ravi
304,1136570,Kolkata,2018-04-14,2018,10,Kolkata Knight Riders,Sunrisers Hyderabad,Eden Gardens,Sunrisers Hyderabad,field,N,Sunrisers Hyderabad,Wickets,5.0,NaN,B Stanlake,"['RV Uthappa', 'CA Lynn', 'N Rana', 'SP Narine...","['WP Saha', 'S Dhawan', 'KS Williamson', 'MK P...",AK Chaudhary,A Nand Kishore
305,1136569,Mumbai,2018-04-14,2018,9,Mumbai Indians,Delhi Daredevils,Wankhede Stadium,Delhi Daredevils,field,N,Delhi Daredevils,Wickets,7.0,NaN,JJ Roy,"['SA Yadav', 'E Lewis', 'Ishan Kishan', 'RG Sh...","['JJ Roy', 'G Gambhir', 'RR Pant', 'GJ Maxwell...",KN Ananthapadmanabhan,Nitin Menon
306,1136568,Bengaluru,2018-04-13,2018,8,Kings XI Punjab,Royal Challengers Bangalore,M.Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Royal Challengers Bangalore,Wickets,4.0,NaN,UT Yadav,"['KL Rahul', 'MA Agarwal', 'AJ Finch', 'Yuvraj...","['Q de Kock', 'BB McCullum', 'V Kohli', 'AB de...",A Deshmukh,S Ravi
307,1136567,Hyderabad,2018-04-12,2018,7,Mumbai Indians,Sunrisers Hyderabad,Rajiv Gandhi International Stadium,Sunrisers Hyderabad,field,N,Sunrisers Hyderabad,Wickets,1.0,NaN,Rashid Khan,"['RG Sharma', 'E Lewis', 'Ishan Kishan', 'SA Y...","['WP Saha', 'S Dhawan', 'KS Williamson', 'MK P...",CK Nandan,NJ Llong
308,1136566,Jaipur,2018-04-11,2018,6,Rajasthan Royals,Delhi Daredevils,Sawai Mansingh Stadium,Delhi Daredevils,field,N,Rajasthan Royals,Runs,10.0,D/L,SV Samson,"['AM Rahane', 'DJM Short', 'BA Stokes', 'SV Sa...","['GJ Maxwell', 'C Munro', 'RR Pant', 'CH Morri...",KN Ananthapadmanabhan,Nitin Menon
309,1136565,Chennai,2018-04-10,2018,5,Kolkata Knight Riders,Chennai Super Kings,MA Chidambaram Stadium,Chennai Super Kings,field,N,Chennai Super Kings,Wickets,5.0,NaN,SW Billings,"['CA Lynn', 'SP Narine', 'RV Uthappa', 'N Rana...","['SR Watson', 'AT Rayudu', 'SK Raina', 'MS Dho...",AK Chaudhary,CB Gaffaney
310,1136564,Hyderabad,2018-04-09,2018,4,Rajasthan Royals,Sunrisers Hyderabad,Rajiv Gandhi International Stadium,Sunrisers Hyderabad,field,N,Sunrisers Hyderabad,Wickets,9.0,NaN,S Dhawan,"['AM Rahane', 'DJM Short', 'SV Samson', 'BA St...","['WP Saha', 'S Dhawan', 'KS Williamson', 'MK P...",NJ Llong,VA Kulkarni
311,1136562,Chandigarh,2018-04-08,2018,2,Delhi Daredevils,Kings XI Punjab,Punjab Cricket Association IS Bindra Stadium,Kings XI Punjab,field,N,Kings XI Punjab,Wickets,6.0,NaN,KL Rahul,"['C Munro', 'G Gambhir', 'SS Iyer', 'V Shankar...","['KL Rahul', 'MA Agarwal', 'Yuvraj Singh', 'KK...",KN Ananthapadmanabhan,RJ Tucker
312,1136563,Kolkata,2018-04-08,2018,3,Royal Challengers Bangalore,Kolkata Knight Riders,Eden Gardens,Kolkata Knight Riders,field,N,Kolkata Knight Riders,Wickets,4.0,NaN,SP Narine,"['BB McCullum', 'Q de Kock', 'V Kohli', 'AB de...","['SP Narine', 'CA Lynn', 'RV Uthappa', 'N Rana...",A Deshmukh,C Shamshuddin
313,1136561,Mumbai,2018-04-07,2018,1,Mumbai Indians,Chennai Super Kings,Wankhede Stadium,Chennai Super Kings,field,N,Chennai Super Kings,Wickets,1.0,NaN,DJ Bravo,"['RG Sharma', 'E Lewis', 'Ishan Kishan', 'SA Y...","['SR Watson', 'AT Rayudu', 'SK Raina', 'KM Jad...",CB Gaffaney,A Nand Kishore

In [221]:
#Isna() function- it detects the Nan values or missing values.

ipl[ipl['WinningTeam'].isna()]    #This matches have NaN values of WinningTeams.

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
205,1178424,Bengaluru,2019-04-30,2019,49,Royal Challengers Bangalore,Rajasthan Royals,M.Chinnaswamy Stadium,Rajasthan Royals,field,NaN,NaN,NoResults,NaN,NaN,NaN,"['V Kohli', 'AB de Villiers', 'MP Stoinis', 'H...","['SV Samson', 'LS Livingstone', 'AM Rahane', '...",NJ Llong,UV Gandhe
437,829813,Bangalore,2015-05-17,2015,55,Royal Challengers Bangalore,Delhi Daredevils,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,NaN,NaN,NoResults,NaN,NaN,NaN,"['V Kohli', 'CH Gayle', 'AB de Villiers', 'Man...","['Q de Kock', 'SS Iyer', 'JP Duminy', 'Yuvraj ...",HDPK Dharmasena,K Srinivasan
464,829763,Bangalore,2015-04-29,2015,29,Royal Challengers Bangalore,Rajasthan Royals,M Chinnaswamy Stadium,Rajasthan Royals,field,NaN,NaN,NoResults,NaN,NaN,NaN,"['CH Gayle', 'V Kohli', 'AB de Villiers', 'Man...","['AM Rahane', 'SR Watson', 'SPD Smith', 'KK Na...",JD Cloete,PG Pathak
708,501265,Delhi,2011-05-21,2011,68,Delhi Daredevils,Pune Warriors,Feroz Shah Kotla,Delhi Daredevils,bat,NaN,NaN,NoResults,NaN,NaN,NaN,"['NV Ojha', 'DA Warner', 'MS Wade', 'CA Ingram...","['MK Pandey', 'JP Faulkner', 'SC Ganguly', 'RV...",SS Hazare,RJ Tucker

In [224]:
# .str.conatins()-

VK=ipl[ipl['Team1Players'].str.contains('V kohli', case=False, na=False)]  

#When Virat kohli in Team 1

VK

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
20,1304100,Mumbai,2022-05-08,2022,54,Royal Challengers Bangalore,Sunrisers Hyderabad,"Wankhede Stadium, Mumbai",Royal Challengers Bangalore,bat,N,Royal Challengers Bangalore,Runs,67.0,NaN,PWH de Silva,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Abhishek Sharma', 'KS Williamson', 'RA Tripa...",BNJ Oxenford,N Pandit
25,1304095,Pune,2022-05-04,2022,49,Royal Challengers Bangalore,Chennai Super Kings,"Maharashtra Cricket Association Stadium, Pune",Chennai Super Kings,field,N,Royal Challengers Bangalore,Runs,13.0,NaN,HV Patel,"['V Kohli', 'F du Plessis', 'GJ Maxwell', 'MK ...","['RD Gaikwad', 'DP Conway', 'RV Uthappa', 'AT ...",KN Ananthapadmanabhan,MA Gough
31,1304089,Mumbai,2022-04-30,2022,43,Royal Challengers Bangalore,Gujarat Titans,"Brabourne Stadium, Mumbai",Royal Challengers Bangalore,bat,N,Gujarat Titans,Wickets,6.0,NaN,R Tewatia,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['WP Saha', 'Shubman Gill', 'B Sai Sudharsan',...",HAS Khalid,VK Sharma
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
925,336006,Bangalore,2008-05-05,2007/08,25,Royal Challengers Bangalore,Kings XI Punjab,M Chinnaswamy Stadium,Kings XI Punjab,field,N,Kings XI Punjab,Wickets,6.0,NaN,S Sreesanth,"['W Jaffer', 'V Kohli', 'CL White', 'JH Kallis...","['SE Marsh', 'JR Hopes', 'RR Sarwan', 'Yuvraj ...",SJ Davis,BR Doctrove
928,336034,Bangalore,2008-05-03,2007/08,21,Royal Challengers Bangalore,Deccan Chargers,M Chinnaswamy Stadium,Deccan Chargers,field,N,Royal Challengers Bangalore,Runs,3.0,NaN,P Kumar,"['B Chipli', 'W Jaffer', 'V Kohli', 'JH Kallis...","['AC Gilchrist', 'VVS Laxman', 'HH Gibbs', 'RG...",BR Doctrove,SL Shastri
935,335996,Bangalore,2008-04-28,2007/08,15,Royal Challengers Bangalore,Chennai Super Kings,M Chinnaswamy Stadium,Chennai Super Kings,bat,N,Chennai Super Kings,Runs,13.0,NaN,MS Dhoni,"['B Chipli', 'W Jaffer', 'LRPL Taylor', 'JH Ka...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'SK Ra...",BR Doctrove,RB Tiffin
939,335992,Bangalore,2008-04-26,2007/08,12,Royal Challengers Bangalore,Rajasthan Royals,M Chinnaswamy Stadium,Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,SR Watson,"['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...","['GC Smith', 'M Rawat', 'YK Pathan', 'SR Watso...",MR Benson,IL Howell
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen